import { CalendarDays, CheckCircle2, Clock3, Flame, XCircle } from 'lucide-react';
import { useMemo } from 'react';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseProgress, EnterpriseStatus, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalMetric, PortalSection, PortalStatus } from '../../../components/portal/PortalUI';
import { activePlayer } from '../portalData';

export function PlayerPortalAttendancePage() {
  const records = activePlayer.attendanceRecords;
  const counts = useMemo(() => records.reduce<Record<string, number>>((result, record) => { result[record.status] = (result[record.status] ?? 0) + 1; return result; }, {}), [records]);
  const rate = Math.round(((counts.present ?? 0) + (counts.late ?? 0) + (counts.excused ?? 0)) / Math.max(records.length, 1) * 100);
  return <div className="admin-page">
    <PageHeader icon={CheckCircle2} eyebrow={bi('Player Portal · Attendance', 'بوابة اللاعب · الحضور')} title={bi('Attendance Journey', 'مسيرة الحضور')} description={bi('See the habits behind your progress with a transparent record of the current preview sessions.', 'شاهد العادات خلف تقدمك عبر سجل شفاف للحصص التجريبية الحالية.')} actions={<PreviewNotice />} />
    <section className="portal-metric-grid"><PortalMetric label={bi('Attendance rate', 'معدل الحضور')} value={`${rate}%`} detail={bi('Derived from records', 'مشتق من السجلات')} tone="green" /><PortalMetric label={bi('Present', 'حاضر')} value={counts.present ?? 0} detail={bi('On time', 'في الموعد')} /><PortalMetric label={bi('Late', 'متأخر')} value={counts.late ?? 0} detail={bi('Follow-up signal', 'مؤشر متابعة')} tone="blue" /><PortalMetric label={bi('Streak', 'التتابع')} value="3" detail={bi('Preview sessions', 'حصص تجريبية')} tone="gold" /></section>
    <PortalSection title={bi('Monthly rhythm', 'إيقاع الشهر')} description={bi('A simple visual rhythm across four preview attendance records.', 'إيقاع بصري بسيط عبر أربعة سجلات حضور تجريبية.')}><div className="attendance-rhythm">{records.map(record => <div className="attendance-day" key={record.id}><span className={`attendance-dot attendance-${record.status}`} /><strong>{new Date(record.date).toLocaleDateString('en-GB', { day: '2-digit' })}</strong><small><BilingualText value={{ en: record.status, ar: ({ present: 'حاضر', absent: 'غائب', late: 'متأخر', excused: 'معذور' } as Record<string, string>)[record.status] }} /></small></div>)}</div><div style={{ marginTop: 18 }}><EnterpriseProgress value={rate} label={bi('Current attendance signal', 'مؤشر الحضور الحالي')} color="green" /></div></PortalSection>
    <PortalSection title={bi('Attendance history', 'سجل الحضور')} description={bi('Local preview marks can be reviewed but are not submitted to a server.', 'يمكن مراجعة علامات المعاينة المحلية لكنها لا ترسل إلى خادم.') }><div className="portal-list">{records.map(record => <div className="portal-list-item" key={record.id}><div><strong><CalendarDays size={13} /> {record.date}</strong><small><BilingualText value={bi('Training session', 'حصة تدريبية')} /></small></div><PortalStatus label={bi(record.status, ({ present: 'حاضر', absent: 'غائب', late: 'متأخر', excused: 'معذور' } as Record<string, string>)[record.status])} tone={record.status === 'present' ? 'active' : record.status === 'late' ? 'pending' : 'neutral'} /></div>)}</div></PortalSection>
    <div className="portal-card-grid"><div className="portal-card"><Flame size={18} color="var(--color-brand-strong)" /><h3><BilingualText value={bi('Keep the rhythm', 'حافظ على الإيقاع')} /></h3><p><BilingualText value={bi('Consistent attendance keeps your development signal honest.', 'الانتظام في الحضور يحافظ على صدق مؤشر تطورك.')} /></p></div><div className="portal-card"><Clock3 size={18} color="var(--color-brand-strong)" /><h3><BilingualText value={bi('Arrival note', 'ملاحظة الوصول')} /></h3><p><BilingualText value={bi('Late and excused marks remain visible for coaching conversations.', 'تبقى علامات التأخر والعذر واضحة لنقاشات التدريب.')} /></p></div><div className="portal-card"><XCircle size={18} color="var(--color-brand-strong)" /><h3><BilingualText value={bi('Preview boundary', 'حدود المعاينة')} /></h3><p><BilingualText value={bi('No attendance claim is sent to production.', 'لا يتم إرسال أي مطالبة بالحضور إلى الإنتاج.')} /></p></div></div>
  </div>;
}
