import { Bell, CreditCard, FileQuestion, HelpCircle, Languages, LockKeyhole, LogOut, MessageSquareText, Moon, Settings, Shield, ShieldCheck, Smartphone } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { PortalSection } from '../../../components/portal/PortalUI';

function EmptyWorkspace({ icon: Icon, title, body }: { icon: typeof CreditCard; title: ReturnType<typeof bi>; body: ReturnType<typeof bi> }) {
  return <div className="player-empty"><span><Icon size={26}/></span><h2><BilingualText value={title}/></h2><p><BilingualText value={body}/></p></div>;
}

export function PlayerPortalSubscriptionPage() { return <div className="player-page"><header className="player-page-heading"><span><BilingualText value={bi('Membership', 'العضوية')}/></span><h1><BilingualText value={bi('Your membership', 'عضويتك')}/></h1><p><BilingualText value={bi('Your verified program and membership information will live here.', 'ستظهر هنا معلومات برنامجك وعضويتك الموثقة.')}/></p></header><PortalSection title={bi('Membership status', 'حالة العضوية')}><EmptyWorkspace icon={ShieldCheck} title={bi('Membership information is not available yet', 'معلومات العضوية غير متاحة بعد')} body={bi('We will show only verified membership details supplied by United Olympics Sports.', 'سنعرض فقط تفاصيل العضوية الموثقة المقدمة من يونايتد أوليمبيكس سبورت.')}/></PortalSection></div>; }
export function PlayerPortalPaymentsPage() { return <div className="player-page"><header className="player-page-heading"><span><BilingualText value={bi('Payments', 'المدفوعات')}/></span><h1><BilingualText value={bi('Financial overview', 'النظرة المالية')}/></h1><p><BilingualText value={bi('A secure home for verified payment history and receipts.', 'مساحة آمنة لسجل المدفوعات والإيصالات الموثقة.')}/></p></header><PortalSection title={bi('Payment records', 'سجلات الدفع')}><EmptyWorkspace icon={CreditCard} title={bi('Financial information is not available yet', 'البيانات المالية غير متاحة بعد')} body={bi('No balance, fee, transaction, or payment method is shown without a verified financial source.', 'لا يتم عرض رصيد أو رسوم أو معاملة أو وسيلة دفع دون مصدر مالي موثق.')}/></PortalSection></div>; }
export function PlayerPortalMessagesPage() { return <div className="player-page"><header className="player-page-heading"><span><BilingualText value={bi('Messages', 'الرسائل')}/></span><h1><BilingualText value={bi('Your conversations', 'محادثاتك')}/></h1><p><BilingualText value={bi('Keep your coach and club communication in one focused place.', 'احتفظ بتواصلك مع المدرب والنادي في مكان واحد واضح.')}/></p></header><PortalSection title={bi('Inbox', 'صندوق الوارد')}><EmptyWorkspace icon={MessageSquareText} title={bi('No messages yet', 'لا توجد رسائل حتى الآن')} body={bi('Verified conversations will appear here when secure messaging is connected.', 'ستظهر المحادثات الموثقة هنا عند ربط خدمة الرسائل الآمنة.')}/></PortalSection></div>; }
export function PlayerPortalNotificationsPage() { return <div className="player-page"><header className="player-page-heading"><span><BilingualText value={bi('Notifications', 'الإشعارات')}/></span><h1><BilingualText value={bi('Stay in the game', 'ابقَ في قلب الحدث')}/></h1><p><BilingualText value={bi('Schedule, attendance, feedback, and membership updates—when they are verified.', 'تحديثات الجدول والحضور والملاحظات والعضوية—بعد توثيقها.')}/></p></header><PortalSection title={bi('Latest updates', 'آخر التحديثات')}><EmptyWorkspace icon={Bell} title={bi('You are all caught up', 'اطلعت على كل جديد')} body={bi('There are no verified notifications for your account.', 'لا توجد إشعارات موثقة لحسابك.')}/></PortalSection></div>; }

const settings = [
  { icon: Languages, title: bi('Language', 'اللغة'), detail: bi('English and Arabic appear together across your portal.', 'تظهر الإنجليزية والعربية معًا في جميع أنحاء بوابتك.') },
  { icon: Moon, title: bi('Appearance', 'المظهر'), detail: bi('Use the appearance control in the top bar.', 'استخدم أداة المظهر في الشريط العلوي.') },
  { icon: Bell, title: bi('Notifications', 'الإشعارات'), detail: bi('Notification preferences will be available after service integration.', 'ستتوفر تفضيلات الإشعارات بعد تكامل الخدمة.') },
  { icon: Shield, title: bi('Privacy', 'الخصوصية'), detail: bi('Only player-owned information is presented here.', 'لا تعرض هنا سوى المعلومات الخاصة باللاعب.') },
  { icon: LockKeyhole, title: bi('Security', 'الأمان'), detail: bi('Authentication controls require a connected identity service.', 'تتطلب عناصر المصادقة خدمة هوية متصلة.') },
  { icon: Smartphone, title: bi('Session', 'الجلسة'), detail: bi('This device is using an explicitly labelled preview session.', 'يستخدم هذا الجهاز جلسة معاينة موضحة بوضوح.') },
  { icon: HelpCircle, title: bi('Help', 'المساعدة'), detail: bi('Contact United Olympics Sports through an approved support channel.', 'تواصل مع يونايتد أوليمبيكس سبورت عبر قناة دعم معتمدة.') },
];
export function PlayerPortalSettingsPage() { const navigate = useNavigate(); return <div className="player-page"><header className="player-page-heading"><span><BilingualText value={bi('Settings', 'الإعدادات')}/></span><h1><BilingualText value={bi('Make it yours', 'اجعلها كما تفضل')}/></h1><p><BilingualText value={bi('Control your experience without changing club-managed athlete records.', 'تحكم في تجربتك دون تغيير سجلات الرياضي التي تديرها الجهة.')}/></p></header><div className="player-settings-list">{settings.map(({ icon: Icon, title, detail }) => <section key={title.en}><span><Icon size={19}/></span><div><h2><BilingualText value={title}/></h2><p><BilingualText value={detail}/></p></div></section>)}</div><button type="button" className="player-logout" onClick={() => navigate('/player/login')}><LogOut size={18}/><BilingualText value={bi('Log out of preview', 'تسجيل الخروج من المعاينة')}/></button></div>; }
export function PlayerSessionDetailPage() { return <div className="player-page"><Link to="/player/schedule" className="player-back-link">← <BilingualText value={bi('Back to Schedule', 'العودة إلى الجدول')}/></Link><EmptyWorkspace icon={FileQuestion} title={bi('Session details are unavailable', 'تفاصيل الحصة غير متاحة')} body={bi('A session can only be opened when its verified record includes complete details.', 'لا يمكن فتح الحصة إلا عندما يتضمن سجلها الموثق التفاصيل الكاملة.')}/></div>; }
