import { CalendarDays, Clock3, MapPin, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseStatus, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalSection, PortalStatus } from '../../../components/portal/PortalUI';
import { activePlayer, activePlayerGroup, activePlayerSport, portalSessions } from '../portalData';

export function PlayerPortalSchedulePage() {
  const sessions = portalSessions.filter(session => session.groupId === activePlayer.groupId);
  return <div className="admin-page">
    <PageHeader icon={CalendarDays} eyebrow={bi('Player Portal · Schedule', 'بوابة اللاعب · الجدول')} title={bi('Training Schedule', 'جدول التدريب')} description={bi('A calm timeline for the next training moments connected to your group.', 'خط زمني هادئ للحصص التدريبية القادمة المرتبطة بمجموعتك.')} actions={<PreviewNotice />} />
    <section className="portal-metric-grid"><article className="portal-metric portal-metric-gold"><strong>{sessions.length}</strong><BilingualText value={bi('Upcoming sessions', 'الحصص القادمة')} /><small><BilingualText value={bi('Linked to your group', 'مرتبطة بمجموعتك')} /></small></article><article className="portal-metric portal-metric-green"><strong>{activePlayerGroup?.playerIds.length ?? 0}</strong><BilingualText value={bi('Group athletes', 'رياضيّو المجموعة')} /></article><article className="portal-metric portal-metric-blue"><strong>{activePlayerGroup?.level.en ?? '—'}</strong><BilingualText value={bi('Current level', 'المستوى الحالي')} /></article><article className="portal-metric"><strong>{activePlayerSport?.name.en ?? '—'}</strong><BilingualText value={bi('Sport track', 'المسار الرياضي')} /></article></section>
    <PortalSection title={bi('Next sessions', 'الحصص القادمة')} description={bi('Preview schedule records with no live booking claim.', 'سجلات جدول تجريبية دون ادعاء حجز مباشر.')}>{sessions.length ? <div className="portal-timeline">{sessions.map(session => <article className="portal-timeline-item" key={session.id}><strong><BilingualText value={activePlayerSport?.name ?? bi('Sport session', 'حصة رياضية')} /></strong><small><CalendarDays size={12} /> {new Date(session.startsAt).toLocaleDateString('en-GB')} · <Clock3 size={12} /> {new Date(session.startsAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</small><div className="portal-session-meta"><span><MapPin size={12} /><BilingualText value={bi('Preview training venue', 'موقع تدريب تجريبي')} /></span><span><UsersRound size={12} /><BilingualText value={activePlayerGroup?.name ?? bi('Training group', 'مجموعة التدريب')} /></span><PortalStatus label={bi('Scheduled', 'مجدولة')} /></div></article>)}</div> : <div className="enterprise-empty"><CalendarDays size={22} /><h3><BilingualText value={bi('No upcoming sessions', 'لا توجد حصص قادمة')} /></h3><p><BilingualText value={bi('Verified schedule records will appear when available.', 'ستظهر سجلات الجدول الموثقة عند توفرها.')} /></p></div>}</PortalSection>
    <div className="portal-action-grid"><Link className="portal-action" to="/player/attendance"><span><BilingualText value={bi('Review attendance', 'مراجعة الحضور')} /></span><EnterpriseStatus label={bi('Preview', 'تجريبي')} tone="info" /></Link><Link className="portal-action" to="/player/profile"><span><BilingualText value={bi('Open athlete profile', 'فتح ملف الرياضي')} /></span><EnterpriseStatus label={bi('Connected', 'مرتبط')} tone="active" /></Link></div>
  </div>;
}
