import { ArrowLeft, Bell, Check, CreditCard, FileQuestion, HelpCircle, Languages, LockKeyhole, LogOut, MessageSquareText, Moon, Send, Shield, ShieldCheck, Smartphone, SunMedium, UserRound } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { demoSessions } from '../../../data/demo/sessions';
import { demoCoaches } from '../../../data/demo/coaches';
import { usePlayerSession } from '../../../portals/player/PlayerSessionContext';
import { useUiSettings } from '../../../ui/theme/useUiSettings';
import type { UiAppearance } from '../../../ui/theme/uiSettings';

type MembershipRecord = { id: string; status: 'active'|'pending'|'expired'; program?: ReturnType<typeof bi>; startDate?: string; endDate?: string };
type PaymentRecord = { id: string; amount: number; currency: string; status: 'completed'|'pending'|'failed'|'refunded'; paidAt?: string };
type PlayerMessage = { id: string; sender: ReturnType<typeof bi>; body: ReturnType<typeof bi>; sentAt: string };
type Conversation = { id: string; title: ReturnType<typeof bi>; messages: PlayerMessage[]; unread: boolean };
type PlayerNotification = { id: string; title: ReturnType<typeof bi>; detail: ReturnType<typeof bi>; createdAt: string; read: boolean; to?: string };
const memberships: MembershipRecord[] = [];
const payments: PaymentRecord[] = [];
const conversations: Conversation[] = [];
const notifications: PlayerNotification[] = [];

function PageHeading({ eyebrow, title, detail }: { eyebrow: ReturnType<typeof bi>; title: ReturnType<typeof bi>; detail: ReturnType<typeof bi> }) {
  return <header className="player-page-heading"><span><BilingualText value={eyebrow}/></span><h1><BilingualText value={title}/></h1><p><BilingualText value={detail}/></p></header>;
}
function EmptyState({ icon: Icon, title, body }: { icon: typeof CreditCard; title: ReturnType<typeof bi>; body: ReturnType<typeof bi> }) {
  return <div className="player-empty"><span><Icon/></span><h2><BilingualText value={title}/></h2><p><BilingualText value={body}/></p></div>;
}

export function PlayerPortalSubscriptionPage() {
  const { player, sport, group } = usePlayerSession();
  const membership = memberships.find(item => item.id === player.id);
  return <div className="player-page"><PageHeading eyebrow={bi('Athlete membership','عضوية الرياضي')} title={bi('Your membership','عضويتك')} detail={bi('Identity and verified programme details in one private space.','الهوية وتفاصيل البرنامج الموثقة في مساحة خاصة واحدة.')}/><section className="membership-shell"><header><img src="/brand/united-olympics-sports-logo.png" alt=""/><div><small>UNITED OLYMPICS SPORTS</small><strong>{player.nameEn}<span lang="ar" dir="rtl">{player.nameAr}</span></strong></div><ShieldCheck/></header><dl><div><dt><BilingualText value={bi('Player ID','رقم اللاعب')}/></dt><dd>{player.id}</dd></div><div><dt><BilingualText value={bi('Sport','الرياضة')}/></dt><dd><BilingualText value={sport?.name ?? bi('Unavailable','غير متاحة')}/></dd></div><div><dt><BilingualText value={bi('Group','المجموعة')}/></dt><dd><BilingualText value={group?.name ?? bi('Unavailable','غير متاحة')}/></dd></div><div><dt><BilingualText value={bi('Membership status','حالة العضوية')}/></dt><dd><BilingualText value={membership ? bi(membership.status, membership.status === 'active' ? 'نشطة' : 'قيد الانتظار') : bi('Awaiting verified record','بانتظار سجل موثق')}/></dd></div></dl></section><section className="record-panel"><header><h2><BilingualText value={bi('Programme and dates','البرنامج والتواريخ')}/></h2><span><BilingualText value={bi('Verified data only','بيانات موثقة فقط')}/></span></header>{membership ? <div>{membership.id}</div> : <EmptyState icon={ShieldCheck} title={bi('Membership details are not available yet','تفاصيل العضوية غير متاحة بعد')} body={bi('Programme, branch, start, end, and renewal information will appear when supplied by the membership service.','ستظهر معلومات البرنامج والفرع والبداية والنهاية والتجديد عند توفيرها من خدمة العضوية.')}/>}</section></div>;
}

export function PlayerPortalPaymentsPage() {
  const { player } = usePlayerSession(); const records = payments.filter(item => item.id === player.id);
  return <div className="player-page"><PageHeading eyebrow={bi('Financial centre','المركز المالي')} title={bi('Payments and receipts','المدفوعات والإيصالات')} detail={bi('A secure view of verified transactions—never estimated balances.','عرض آمن للمعاملات الموثقة—دون أرصدة تقديرية.')}/><section className="payment-summary-grid"><article><CreditCard/><span><BilingualText value={bi('Current balance','الرصيد الحالي')}/></span><strong>—</strong><small><BilingualText value={bi('Awaiting financial service','بانتظار الخدمة المالية')}/></small></article><article><Check/><span><BilingualText value={bi('Payment status','حالة الدفع')}/></span><strong>—</strong><small><BilingualText value={bi('No verified status','لا توجد حالة موثقة')}/></small></article></section><section className="record-panel"><header><h2><BilingualText value={bi('Payment history','سجل المدفوعات')}/></h2><div className="status-legend"><span>● <BilingualText value={bi('Paid','مدفوع')}/></span><span>● <BilingualText value={bi('Pending','قيد الانتظار')}/></span><span>● <BilingualText value={bi('Failed / Refunded','فشل / مسترد')}/></span></div></header>{records.length ? records.map(record => <article key={record.id}>{record.amount} {record.currency}</article>) : <EmptyState icon={CreditCard} title={bi('Financial information is not available yet','البيانات المالية غير متاحة بعد')} body={bi('Payments, amounts, methods, and receipt actions appear only after verified records are connected.','لا تظهر المدفوعات والمبالغ والوسائل وإجراءات الإيصالات إلا بعد ربط سجلات موثقة.')}/>}</section></div>;
}

export function PlayerPortalMessagesPage() {
  return <div className="player-page messages-page"><PageHeading eyebrow={bi('Communication','التواصل')} title={bi('Messages','الرسائل')} detail={bi('Your private communication centre.','مركز تواصلك الخاص.')}/><section className="messages-shell"><aside><label><BilingualText value={bi('Conversations','المحادثات')}/><input type="search" placeholder="Search | بحث" disabled={!conversations.length}/></label>{conversations.length ? conversations.map(item => <button key={item.id}><UserRound/><BilingualText value={item.title}/>{item.unread && <i/>}</button>) : <EmptyState icon={MessageSquareText} title={bi('No conversations yet','لا توجد محادثات بعد')} body={bi('Verified coach or support conversations will appear here.','ستظهر محادثات المدرب أو الدعم الموثقة هنا.')}/>}</aside><div className="message-panel"><div className="message-panel-empty"><MessageSquareText/><h2><BilingualText value={bi('Choose a conversation','اختر محادثة')}/></h2><p><BilingualText value={bi('Secure messaging is not connected for this account.','خدمة الرسائل الآمنة غير متصلة بهذا الحساب.')}/></p></div><form><textarea disabled aria-label="Message | الرسالة" placeholder="Write a message | اكتب رسالة"/><button disabled><Send/><BilingualText value={bi('Send','إرسال')}/></button></form></div></section></div>;
}

export function PlayerPortalNotificationsPage() {
  const today = notifications.filter(item => new Date(item.createdAt).toDateString() === new Date().toDateString()); const earlier = notifications.filter(item => !today.includes(item));
  return <div className="player-page"><PageHeading eyebrow={bi('Your updates','تحديثاتك')} title={bi('Notifications','الإشعارات')} detail={bi('Schedule, attendance, feedback, and membership signals in one place.','إشارات الجدول والحضور والملاحظات والعضوية في مكان واحد.')}/><div className="notification-toolbar"><div><span><BilingualText value={bi('All','الكل')}/></span><span><BilingualText value={bi('Unread','غير المقروء')}/></span></div><button disabled><Check/><BilingualText value={bi('Mark all read','تحديد الكل كمقروء')}/></button></div>{notifications.length ? [['Today | اليوم',today],['Earlier | سابقًا',earlier]].map(([label,items]) => <section className="notification-group" key={label as string}><h2>{label as string}</h2>{(items as PlayerNotification[]).map(item => <article key={item.id}><Bell/><BilingualText value={item.title}/></article>)}</section>) : <section className="record-panel"><EmptyState icon={Bell} title={bi('You are all caught up','اطلعت على كل جديد')} body={bi('Verified updates will be grouped here by date and read state.','سيتم تجميع التحديثات الموثقة هنا حسب التاريخ وحالة القراءة.')}/></section>}</div>;
}

const appearanceOptions: Array<{ value: UiAppearance; icon: typeof Moon; label: ReturnType<typeof bi> }> = [{value:'light',icon:SunMedium,label:bi('Light','فاتح')},{value:'dark',icon:Moon,label:bi('Dark','داكن')},{value:'system',icon:Smartphone,label:bi('System','النظام')}];
export function PlayerPortalSettingsPage() {
  const navigate = useNavigate(); const { gateway, authSession } = usePlayerSession(); const ui = useUiSettings();
  const logout = async () => { await gateway.signOut(); window.sessionStorage.removeItem('uos:player-preview-session:v1'); navigate('/player/login',{replace:true}); };
  return <div className="player-page"><PageHeading eyebrow={bi('Personal controls','عناصر التحكم الشخصية')} title={bi('Settings','الإعدادات')} detail={bi('Choose how your athlete space looks and reads.','اختر شكل وطريقة عرض مساحتك الرياضية.')}/><div className="settings-sections"><section><header><Moon/><div><h2><BilingualText value={bi('Appearance','المظهر')}/></h2><p><BilingualText value={bi('Choose a theme or follow your device.','اختر مظهرًا أو اتبع إعداد جهازك.')}/></p></div></header><div className="settings-choice">{appearanceOptions.map(({value,icon:Icon,label}) => <button key={value} aria-pressed={ui.appearance === value} onClick={() => ui.setAppearance(value)}><Icon/><BilingualText value={label}/></button>)}</div></section><section><header><Languages/><div><h2><BilingualText value={bi('Language order','ترتيب اللغة')}/></h2><p><BilingualText value={bi('Choose which language appears first.','اختر اللغة التي تظهر أولًا.')}/></p></div></header><div className="settings-choice"><button aria-pressed={ui.bilingualOrder === 'en-first'} onClick={() => ui.setSetting('bilingualOrder','en-first')}>English first<span lang="ar">الإنجليزية أولًا</span></button><button aria-pressed={ui.bilingualOrder === 'ar-first'} onClick={() => ui.setSetting('bilingualOrder','ar-first')}>العربية أولًا<span>Arabic first</span></button></div></section><section className="disabled-setting" aria-disabled="true"><header><Bell/><div><h2><BilingualText value={bi('Notification preferences','تفضيلات الإشعارات')}/></h2><p><BilingualText value={bi('Available after notification service integration.','تتوفر بعد تكامل خدمة الإشعارات.')}/></p></div></header></section><section className="session-setting"><header><Shield/><div><h2><BilingualText value={bi('Current session','الجلسة الحالية')}/></h2><p>{authSession.playerId} · <BilingualText value={bi('Explicit preview mode','وضع المعاينة الصريح')}/></p></div></header></section></div><button type="button" className="player-logout" onClick={logout}><LogOut/><BilingualText value={bi('Log out','تسجيل الخروج')}/></button><Link className="settings-help" to="/"><HelpCircle/><BilingualText value={bi('Help and public website','المساعدة والموقع العام')}/></Link></div>;
}

export function PlayerSessionDetailPage() {
  const { sessionId } = useParams(); const { player, sport, group } = usePlayerSession(); const session = demoSessions.find(item => item.id === sessionId && item.groupId === player.groupId); const coach = demoCoaches.find(item => item.groupIds.includes(player.groupId ?? ''));
  if (!session) return <div className="player-page"><Link to="/player/schedule" className="player-back-link"><ArrowLeft/><BilingualText value={bi('Back to Schedule','العودة إلى الجدول')}/></Link><EmptyState icon={FileQuestion} title={bi('Session not found','لم يتم العثور على الحصة')} body={bi('This session does not exist or does not belong to your training group.','هذه الحصة غير موجودة أو لا تنتمي إلى مجموعتك التدريبية.')}/></div>;
  return <div className="player-page session-detail-page"><Link to="/player/schedule" className="player-back-link"><ArrowLeft/><BilingualText value={bi('Back to Schedule','العودة إلى الجدول')}/></Link><PageHeading eyebrow={bi('Session detail','تفاصيل الحصة')} title={sport?.name ?? bi('Training session','حصة تدريبية')} detail={session.status}/><section className="session-detail-card"><time dateTime={session.startsAt}><strong>{new Date(session.startsAt).toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</strong><span>{new Date(session.startsAt).toLocaleDateString('ar-AE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</span></time><dl><div><dt><BilingualText value={bi('Time','الوقت')}/></dt><dd>{new Date(session.startsAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt><BilingualText value={bi('Group','المجموعة')}/></dt><dd><BilingualText value={group?.name ?? bi('Unavailable','غير متاحة')}/></dd></div><div><dt><BilingualText value={bi('Coach','المدرب')}/></dt><dd><BilingualText value={coach ? bi(coach.nameEn.replace(' Preview',''),coach.nameAr.replace(' تجريبي','')) : bi('To be confirmed','قيد التأكيد')}/></dd></div><div><dt><BilingualText value={bi('Location','الموقع')}/></dt><dd><BilingualText value={bi('To be confirmed','قيد التأكيد')}/></dd></div></dl></section></div>;
}
