import { Activity, Contact, IdCard, LockKeyhole, ShieldCheck, UsersRound } from 'lucide-react';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { PlayerPortrait } from '../../../components/player/PlayerIdentity';
import { demoCoaches } from '../../../data/demo/coaches';
import { getBranch } from '../../../data/demo/selectors';
import { usePlayerSession } from '../../../portals/player/PlayerSessionContext';

function ProfileSection({ icon: Icon, title, children }: { icon: typeof IdCard; title: ReturnType<typeof bi>; children: React.ReactNode }) { return <section className="profile-section"><header><Icon/><h2><BilingualText value={title}/></h2></header><dl>{children}</dl></section>; }
function Field({ label, children, locked = true }: { label: ReturnType<typeof bi>; children: React.ReactNode; locked?: boolean }) { return <div className="profile-field"><dt><BilingualText value={label}/>{locked && <LockKeyhole aria-label="Read only | للقراءة فقط"/>}</dt><dd>{children}</dd></div>; }
export function PlayerPortalProfilePage() {
  const { player, sport, group } = usePlayerSession(); const coach = demoCoaches.find(item => item.groupIds.includes(player.groupId ?? '')); const branch = getBranch(coach?.branchIds[0]);
  return <div className="player-page"><header className="profile-hero"><PlayerPortrait player={player} size="medium"/><div><span><BilingualText value={bi('Athlete profile','ملف الرياضي')}/></span><h1>{player.nameEn}<b lang="ar" dir="rtl">{player.nameAr}</b></h1><p>{player.id}</p></div><span className="profile-status"><ShieldCheck/><BilingualText value={player.status}/></span></header><div className="profile-grid"><ProfileSection icon={IdCard} title={bi('Identity','الهوية')}><Field label={bi('English name','الاسم بالإنجليزية')}>{player.nameEn}</Field><Field label={bi('Arabic name','الاسم بالعربية')}><span lang="ar" dir="rtl">{player.nameAr}</span></Field><Field label={bi('Player ID','رقم اللاعب')}>{player.id}</Field><Field label={bi('Age','العمر')}>{player.age ?? '—'}</Field><Field label={bi('Birth date','تاريخ الميلاد')}>{player.dateOfBirth ?? '—'}</Field></ProfileSection><ProfileSection icon={Activity} title={bi('Sports profile','الملف الرياضي')}><Field label={bi('Sport','الرياضة')}><BilingualText value={sport?.name ?? bi('Unavailable','غير متاحة')}/></Field><Field label={bi('Level','المستوى')}><BilingualText value={player.level}/></Field></ProfileSection><ProfileSection icon={UsersRound} title={bi('Training context','سياق التدريب')}><Field label={bi('Group','المجموعة')}><BilingualText value={group?.name ?? bi('Unavailable','غير متاحة')}/></Field><Field label={bi('Coach','المدرب')}><BilingualText value={coach ? bi(coach.nameEn.replace(' Preview',''),coach.nameAr.replace(' تجريبي','')) : bi('To be confirmed','قيد التأكيد')}/></Field><Field label={bi('Branch','الفرع')}><BilingualText value={branch?.name ?? bi('To be confirmed','قيد التأكيد')}/></Field></ProfileSection><ProfileSection icon={Contact} title={bi('Contact','التواصل')}><Field label={bi('Contact details','بيانات التواصل')}>—</Field></ProfileSection><ProfileSection icon={ShieldCheck} title={bi('Membership','العضوية')}><Field label={bi('Membership record','سجل العضوية')}><BilingualText value={bi('Awaiting verified source','بانتظار مصدر موثق')}/></Field></ProfileSection></div></div>;
}
