import { Activity, ArrowUpRight, BarChart3, Radar, TrendingUp } from 'lucide-react';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseProgress, EnterpriseSparkline, EnterpriseTable, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalMetric, PortalSection, PortalTrend } from '../../../components/portal/PortalUI';
import { getLatestPlayerMetrics, getPlayerOverall } from '../../../data/demo/selectors';
import { activePlayer, activePlayerSport } from '../portalData';

function radarPoints(values: number[]) {
  return values.map((value, index) => { const angle = (Math.PI * 2 * index) / values.length - Math.PI / 2; const radius = 68 * (value / 100); return `${95 + Math.cos(angle) * radius},${95 + Math.sin(angle) * radius}`; }).join(' ');
}

export function PlayerPortalPerformancePage() {
  const metrics = getLatestPlayerMetrics(activePlayer.id);
  const score = getPlayerOverall(activePlayer.id);
  const values = metrics.map(metric => metric.current?.value ?? 0);
  return <div className="admin-page">
    <PageHeader icon={Radar} eyebrow={bi('Player Portal · Performance', 'بوابة اللاعب · الأداء')} title={bi('Performance Lab', 'مختبر الأداء')} description={bi('Understand how your sport-specific skills are moving across the latest preview evaluation.', 'افهم كيف تتطور مهاراتك الخاصة بالرياضة عبر أحدث تقييم تجريبي.')} actions={<PreviewNotice />} />
    <section className="portal-metric-grid"><PortalMetric label={bi('Overall score', 'الدرجة الإجمالية')} value={`${score}/100`} detail={bi('Latest preview evaluation', 'أحدث تقييم تجريبي')} /><PortalMetric label={bi('Skill records', 'سجلات المهارات')} value={metrics.length} detail={activePlayerSport?.name} tone="blue" /><PortalMetric label={bi('Trend', 'الاتجاه')} value="+6" detail={bi('Compared with prior record', 'مقارنة بالسجل السابق')} tone="green" /><PortalMetric label={bi('Evaluation date', 'تاريخ التقييم')} value="28 Aug" detail={bi('Preview timestamp', 'تاريخ تجريبي')} tone="gold" /></section>
    <section className="enterprise-grid-2"><PortalSection title={bi('Skill radar', 'رادار المهارات')} description={bi('A visual profile across sport-specific metrics.', 'ملف بصري عبر مؤشرات خاصة بالرياضة.')}><div className="portal-radar"><svg viewBox="0 0 190 190" role="img" aria-label="Skill radar preview | معاينة رادار المهارات"><polygon points="95,27 159,74 135,151 55,151 31,74" fill="none" stroke="var(--color-border-strong)" /><polygon points="95,48 140,81 123,137 67,137 50,81" fill="none" stroke="var(--color-border)" /><polygon points={radarPoints(values)} /><circle cx="95" cy="95" r="3" /><text x="95" y="15" textAnchor="middle" fill="currentColor" fontSize="8">{metrics[0]?.definition.name.en}</text><text x="175" y="78" textAnchor="middle" fill="currentColor" fontSize="8">{metrics[1]?.definition.name.en}</text><text x="145" y="174" textAnchor="middle" fill="currentColor" fontSize="8">{metrics[2]?.definition.name.en}</text><text x="45" y="174" textAnchor="middle" fill="currentColor" fontSize="8">{metrics[3]?.definition.name.en}</text><text x="15" y="78" textAnchor="middle" fill="currentColor" fontSize="8">{metrics[4]?.definition.name.en}</text></svg></div></PortalSection><PortalSection title={bi('Training pulse', 'نبض التدريب')} description={bi('Recent score movement from local preview records.', 'حركة الدرجات الحديثة من سجلات المعاينة المحلية.')}><PortalTrend label={bi('Current score', 'الدرجة الحالية')} value={`${score}/100`} values={values} color="green" /><div style={{ marginTop: 12 }}><EnterpriseProgress value={score} label={bi('Development signal', 'مؤشر التطور')} color="green" /></div><div style={{ marginTop: 14 }}><EnterpriseSparkline values={[62, 68, 66, 73, 71, 76]} color="green" /></div></PortalSection></section>
    <PortalSection title={bi('Metric detail', 'تفاصيل المؤشرات')} description={bi('Each row keeps the previous and latest preview values visible.', 'يحافظ كل صف على القيم السابقة والأحدث للمعاينة.') }><EnterpriseTable caption={bi('Player performance metrics', 'مؤشرات أداء اللاعب')}><thead><tr>{[bi('Metric', 'المؤشر'), bi('Latest', 'الأحدث'), bi('Previous', 'السابق'), bi('Change', 'التغيير'), bi('Coverage', 'التغطية')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{metrics.map(metric => { const current = metric.current?.value ?? 0; const previous = metric.previous?.value ?? 0; return <tr key={metric.definition.id}><td><strong><BilingualText value={metric.definition.name} /></strong><small><BilingualText value={activePlayerSport?.name ?? bi('Sport', 'الرياضة')} /></small></td><td><strong>{current}</strong></td><td>{previous}</td><td><span className="metric-trend up"><ArrowUpRight size={13} /> +{current - previous}</span></td><td><EnterpriseProgress value={current} /></td></tr>; })}</tbody></EnterpriseTable></PortalSection>
    <div className="portal-preview-card"><div className="portal-preview-card-head"><span><TrendingUp size={16} /></span><div><strong><BilingualText value={bi('Coach context', 'سياق المدرب')} /></strong><small><BilingualText value={bi('Preview evaluation only', 'تقييم تجريبي فقط')} /></small></div></div><p><BilingualText value={bi('Use these signals as a conversation starter for the next training session; they are not a certified ranking.', 'استخدم هذه المؤشرات كبداية للنقاش في الحصة القادمة؛ فهي ليست ترتيبًا معتمدًا.')} /></p></div>
  </div>;
}
