import { ArrowRight, Focus, ShieldCheck, Sparkles } from 'lucide-react';
import type { Player } from '../../domain/contracts';
import { getSportMetrics } from '../../data/demo/selectors';
import { BilingualText, bi } from '../bilingual/BilingualText';

export function CoachFeedbackPanel({ player }: { player: Player }) {
  const definitions = getSportMetrics(player.sportId);
  return <div className="coach-feedback-view">{player.coachFeedback.length ? player.coachFeedback.map(item => <article className="feedback-card" key={item.id}><header><span className="coach-demo-avatar"><ShieldCheck /></span><div><BilingualText value={bi('Coach Evaluation', 'تقييم المدرب')} /><small>{item.coachId} · <BilingualText value={bi('Anonymous Preview Coach', 'مدرب تجريبي مجهول')} /></small></div><time>{item.createdAt}</time></header><div className="feedback-summary"><BilingualText value={bi('Summary', 'الملخص')} /><p><BilingualText value={item.summary} /></p></div><div className="feedback-columns"><section><h3><Sparkles /><BilingualText value={bi('Strengths', 'نقاط القوة')} /></h3>{item.strengths.map(value => <BilingualText key={value.en} value={value} />)}</section><section><h3><Focus /><BilingualText value={bi('Focus Areas', 'نقاط التركيز')} /></h3>{item.focusAreas.map(value => <BilingualText key={value.en} value={value} />)}</section></div><div className="metric-change-list"><BilingualText value={bi('Metric Changes', 'تغير المؤشرات')} />{item.metricChanges.map(change => { const definition = definitions.find(metric => metric.id === change.metricId); return <span key={change.metricId}>{definition && <BilingualText value={definition.name} />}<strong>{change.previousValue}</strong><ArrowRight /><strong>{change.currentValue}</strong></span>; })}</div></article>) : <div className="future-panel"><BilingualText value={bi('No preview coach feedback', 'لا توجد تقييمات مدرب تجريبية')} /><p><BilingualText value={bi('The contract is ready for future coach evaluations.', 'العقد جاهز لتقييمات المدربين المستقبلية.')} /></p></div>}</div>;
}
