import { BarChart3, CalendarCheck, Gauge, TrendingUp } from 'lucide-react';
import type { Player } from '../../domain/contracts';
import { getLatestPlayerMetrics, getPlayerOverall } from '../../data/demo/selectors';
import { BilingualText, bi } from '../bilingual/BilingualText';
import { StatCard, Trend } from './AdminUI';

export function PlayerPerformance({ player }: { player: Player }) {
  const metrics = getLatestPlayerMetrics(player.id); const overall = getPlayerOverall(player.id); const latestDate = metrics[0]?.current?.recordedAt ?? '—';
  const averagePrevious = metrics.length ? Math.round(metrics.reduce((sum, metric) => sum + (metric.previous?.value ?? 0), 0) / metrics.length) : 0;
  return <div className="performance-view"><section className="admin-stat-grid compact"><StatCard label={bi('Overall Development', 'التطور العام')} value={`${overall} / 100`} icon={Gauge} /><StatCard label={bi('Latest Evaluation', 'آخر تقييم')} value={latestDate} icon={CalendarCheck} /><StatCard label={bi('Performance Trend', 'اتجاه الأداء')} value={`+${overall - averagePrevious}`} icon={TrendingUp} note={bi('Preview score change', 'تغير الدرجة التجريبية')} /></section><div className="panel-heading section-heading-inline"><div><BilingualText value={bi('Sport Metrics', 'مؤشرات الرياضة')} /><small><BilingualText value={bi('Definitions loaded dynamically from the player sport', 'تعريفات محملة ديناميكيًا من رياضة اللاعب')} /></small></div><BarChart3 /></div><section className="performance-metric-grid">{metrics.map(({ definition, current, previous }) => <article className="performance-metric-card" key={definition.id}><div className="metric-card-head"><BilingualText value={definition.name} /><Trend current={current?.value ?? 0} previous={previous?.value ?? 0} /></div><div className="metric-score"><strong>{current?.value ?? '—'}</strong><span>/ 100 | من 100</span></div><div className="metric-bar" aria-label={`${definition.name.en} ${current?.value ?? 0} of 100 | ${definition.name.ar} ${current?.value ?? 0} من 100`}><span style={{ width: `${current?.value ?? 0}%` }} /></div><dl><div><dt><BilingualText value={bi('Previous Value', 'القيمة السابقة')} /></dt><dd>{previous?.value ?? '—'}</dd></div><div><dt><BilingualText value={bi('Recorded Date', 'تاريخ التسجيل')} /></dt><dd>{current?.recordedAt ?? '—'}</dd></div></dl></article>)}</section><section className="admin-panel coach-assessment-summary"><div><BilingualText value={bi('Coach Assessment', 'تقييم المدرب')} /><p><BilingualText value={bi('Structured preview feedback is available in the Coach Feedback tab. No transmission to other portals is claimed.', 'يتوفر تقييم تجريبي منظم في تبويب تقييمات المدربين. لا يُدّعى إرساله إلى أي بوابات أخرى.')} /></p></div><span className="preview-badge"><span className="preview-dot" /><BilingualText value={bi('Preview Data', 'بيانات تجريبية')} /></span></section></div>;
}
