import { Activity, Award, CalendarDays, CheckCircle2, ClipboardCheck, FileText, MessageCircle, Send, Target, UserRound, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseProgress, EnterpriseStatus, EnterpriseTable, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalMetric, PortalPreviewCard, PortalSection, PortalStatus } from '../../../components/portal/PortalUI';
import { demoPlayers } from '../../../data/demo/players';
import { getGroup, getLatestPlayerMetrics, getPlayerOverall, getSport } from '../../../data/demo/selectors';
import { activeCoach, portalCoachPlayers, portalGroups, portalPrograms, portalSessions } from '../portalData';
import { UiButton } from '../../../components/ui/UiPrimitives';

export function CoachPortalSchedulePage() {
  const sessions = portalSessions.filter(session => activeCoach.groupIds.includes(session.groupId));
  return <div className="admin-page"><PageHeader icon={CalendarDays} eyebrow={bi('Coach Portal · Schedule', 'بوابة المدرب · الجدول')} title={bi('Training Schedule', 'جدول التدريب')} description={bi('Organize the next sessions around your assigned groups and coaching responsibilities.', 'نظم الحصص القادمة حول مجموعاتك ومسؤولياتك التدريبية.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Upcoming sessions', 'الحصص القادمة')} value={sessions.length} /><PortalMetric label={bi('Assigned groups', 'المجموعات المكلف بها')} value={activeCoach.groupIds.length} tone="green" /><PortalMetric label={bi('Athletes', 'الرياضيون')} value={portalCoachPlayers.length} tone="blue" /><PortalMetric label={bi('Attendance tasks', 'مهام الحضور')} value={sessions.length} tone="gold" /></section><PortalSection title={bi('Coach calendar', 'تقويم المدرب')} description={bi('Preview sessions linked to the active coach assignment.', 'حصص تجريبية مرتبطة بتكليف المدرب الحالي.') }><div className="portal-timeline">{sessions.map(session => <article className="portal-timeline-item" key={session.id}><strong><BilingualText value={getSport(session.sportId)?.name ?? bi('Sport session', 'حصة رياضية')} /></strong><small>{session.id} · {new Date(session.startsAt).toLocaleDateString('en-GB')} · {new Date(session.startsAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</small><div className="portal-session-meta"><span><UsersRound size={12} /> {getGroup(session.groupId)?.name.en ?? session.groupId}</span><PortalStatus label={bi('Ready for preview', 'جاهزة للمعاينة')} tone="active" /></div></article>)}</div></PortalSection><div className="portal-action-grid"><Link className="portal-action" to="/coach/attendance"><span><BilingualText value={bi('Open attendance queue', 'فتح قائمة الحضور')} /><small><BilingualText value={bi('Mark local preview states', 'تحديد حالات المعاينة المحلية')} /></small></span><CheckCircle2 size={16} /></Link><Link className="portal-action" to="/coach/evaluations"><span><BilingualText value={bi('Review evaluations', 'مراجعة التقييمات')} /><small><BilingualText value={bi('Use sport-specific signals', 'استخدام مؤشرات خاصة بالرياضة')} /></small></span><Activity size={16} /></Link></div></div>;
}

export function CoachPortalGroupsPage() {
  const groups = portalGroups.filter(group => activeCoach.groupIds.includes(group.id));
  return <div className="admin-page"><PageHeader icon={UsersRound} eyebrow={bi('Coach Portal · Groups', 'بوابة المدرب · المجموعات')} title={bi('Training Groups', 'مجموعات التدريب')} description={bi('Your assigned teams, capacity context and next operational step.', 'فرقك المكلف بها وسياق السعة والخطوة التشغيلية القادمة.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Assigned groups', 'المجموعات المكلف بها')} value={groups.length} /><PortalMetric label={bi('Roster size', 'حجم القائمة')} value={groups.reduce((sum, group) => sum + group.playerIds.length, 0)} tone="green" /><PortalMetric label={bi('Programs', 'البرامج')} value={new Set(groups.flatMap(group => group.programIds)).size} tone="blue" /><PortalMetric label={bi('Coach scope', 'نطاق المدرب')} value={activeCoach.nameEn} /></section><PortalSection title={bi('Group roster', 'قائمة المجموعات')}><div className="portal-card-grid">{groups.map(group => <article className="portal-card" key={group.id}><div className="child-card-head"><span className="portal-card-icon"><UsersRound size={16} /></span><div><h3><BilingualText value={group.name} /></h3><small><BilingualText value={group.level} /></small></div><EnterpriseStatus label={bi('Active', 'نشط')} tone="active" /></div><p><BilingualText value={group.ageGroup} /> · {group.playerIds.length} <BilingualText value={bi('players', 'لاعبين')} /></p><div style={{ marginTop: 13 }}><EnterpriseProgress value={Math.min(100, group.playerIds.length * 20)} label={bi('Roster capacity signal', 'مؤشر سعة القائمة')} /></div><Link className="admin-link-button" to={`/coach/groups/${group.id}`}><BilingualText value={bi('Open group workspace', 'فتح مساحة المجموعة')} /></Link></article>)}</div></PortalSection></div>;
}

export function CoachPortalPlayersPage() {
  const [query, setQuery] = useState('');
  const [group, setGroup] = useState('all');
  const players = portalCoachPlayers.filter(player => (group === 'all' || player.groupId === group) && `${player.nameEn} ${player.nameAr} ${player.id}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="admin-page"><PageHeader icon={UserRound} eyebrow={bi('Coach Portal · Players', 'بوابة المدرب · اللاعبون')} title={bi('Coach Roster', 'قائمة المدرب')} description={bi('Search the athlete records assigned to this coaching workspace.', 'ابحث في سجلات الرياضيين المكلفين بمساحة التدريب هذه.')} actions={<PreviewNotice />} /><div className="enterprise-toolbar"><label className="enterprise-search"><span>⌕</span><span className="sr-only"><BilingualText value={bi('Search players', 'البحث عن اللاعبين')} /></span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search players | البحث عن اللاعبين" /></label><label className="enterprise-field"><BilingualText value={bi('Group', 'المجموعة')} /><select value={group} onChange={event => setGroup(event.target.value)}><option value="all">All groups | كل المجموعات</option>{activeCoach.groupIds.map(id => <option value={id} key={id}>{getGroup(id)?.name.en ?? id}</option>)}</select></label><span className="enterprise-result"><BilingualText value={bi(`${players.length} players`, `${players.length} لاعبين`)} /></span></div><EnterpriseTable caption={bi('Coach roster', 'قائمة المدرب')}><thead><tr>{[bi('Player', 'اللاعب'), bi('Sport', 'الرياضة'), bi('Group', 'المجموعة'), bi('Attendance', 'الحضور'), bi('Performance', 'الأداء'), bi('Action', 'الإجراء')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{players.map(player => <tr key={player.id}><td><strong><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></strong><small>{player.id}</small></td><td><BilingualText value={getSport(player.sportId)?.name ?? bi(player.sportId, player.sportId)} /></td><td><BilingualText value={getGroup(player.groupId)?.name ?? bi('Not assigned', 'غير معين')} /></td><td><strong>{Math.round(((player.attendanceSummary?.attended ?? 0) / Math.max(player.attendanceSummary?.scheduled ?? 1, 1)) * 100)}%</strong></td><td><strong>{getPlayerOverall(player.id)}/100</strong></td><td><Link className="admin-link-button" to={`/coach/players/${player.id}`}><BilingualText value={bi('Open athlete', 'فتح الرياضي')} /></Link></td></tr>)}</tbody></EnterpriseTable></div>;
}

export function CoachPortalAttendancePage() {
  const [marks, setMarks] = useState<Record<string, string>>({});
  const groupPlayers = portalCoachPlayers;
  const mark = (id: string, value: string) => setMarks(current => ({ ...current, [id]: value }));
  return <div className="admin-page"><PageHeader icon={CheckCircle2} eyebrow={bi('Coach Portal · Attendance', 'بوابة المدرب · الحضور')} title={bi('Session Attendance', 'حضور الجلسة')} description={bi('Mark the current coaching roster locally for a truthful operational workflow preview.', 'حدد قائمة التدريب الحالية محليًا لمعاينة سير عمل تشغيلي صادق.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Roster in session', 'القائمة في الجلسة')} value={groupPlayers.length} /><PortalMetric label={bi('Marked present', 'تم تحديد الحضور')} value={Object.values(marks).filter(value => value === 'present').length} tone="green" /><PortalMetric label={bi('Needs review', 'تحتاج إلى مراجعة')} value={Object.values(marks).filter(value => value === 'absent').length} tone="gold" /><PortalMetric label={bi('Session state', 'حالة الجلسة')} value="Preview" tone="blue" /></section><PortalSection title={bi('Attendance queue', 'قائمة الحضور')} description={bi('Every mark remains local to this preview session.', 'تبقى كل علامة محلية لجلسة المعاينة هذه.') }><EnterpriseTable caption={bi('Coach attendance queue', 'قائمة حضور المدرب')}><thead><tr>{[bi('Player', 'اللاعب'), bi('Group', 'المجموعة'), bi('Current record', 'السجل الحالي'), bi('Local mark', 'العلامة المحلية')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{groupPlayers.map(player => <tr key={player.id}><td><strong><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></strong><small>{player.id}</small></td><td><BilingualText value={getGroup(player.groupId)?.name ?? bi('Group', 'المجموعة')} /></td><td>{player.attendanceSummary?.attended ?? 0}/{player.attendanceSummary?.scheduled ?? 0}</td><td><select className="inline-select" value={marks[player.id] ?? ''} onChange={event => mark(player.id, event.target.value)}><option value="">Select status | اختر الحالة</option><option value="present">Present | حاضر</option><option value="absent">Absent | غائب</option><option value="late">Late | متأخر</option><option value="excused">Excused | معذور</option></select></td></tr>)}</tbody></EnterpriseTable></PortalSection></div>;
}

export function CoachPortalEvaluationsPage() {
  const [notice, setNotice] = useState(false);
  return <div className="admin-page"><PageHeader icon={ClipboardCheck} eyebrow={bi('Coach Portal · Evaluations', 'بوابة المدرب · التقييمات')} title={bi('Evaluations Studio', 'استوديو التقييمات')} description={bi('Review sport-specific signals and prepare a local coaching note.', 'راجع مؤشرات خاصة بالرياضة وجهز ملاحظة تدريب محلية.')} actions={<PreviewNotice />} /><section className="portal-card-grid">{portalCoachPlayers.map(player => { const score = getPlayerOverall(player.id); return <article className="portal-card" key={player.id}><div className="child-card-head"><span className="portal-card-icon"><Target size={16} /></span><div><h3>{player.nameEn}</h3><small lang="ar" dir="rtl">{player.nameAr}</small></div><strong className="score-figure">{score}</strong></div><p><BilingualText value={getSport(player.sportId)?.name ?? bi(player.sportId, player.sportId)} /></p><EnterpriseProgress value={score} label={bi('Overall signal', 'المؤشر الإجمالي')} color="green" /><UiButton variant="outline" type="button" onClick={() => setNotice(true)}><ClipboardCheck size={13} /><BilingualText value={bi('Save note locally', 'حفظ الملاحظة محليًا')} /></UiButton></article>; })}</section>{notice && <div className="preview-notice" role="status"><BilingualText value={bi('Evaluation note updated locally', 'تم تحديث ملاحظة التقييم محليًا')} /></div>}<PortalPreviewCard title={bi('Evaluation boundary', 'حدود التقييم')} description={bi('A local note is a product interaction preview, not a certified assessment or database write.', 'الملاحظة المحلية معاينة لتفاعل المنتج وليست تقييمًا معتمدًا أو كتابة في قاعدة بيانات.')} /></div>;
}

export function CoachPortalProgramsPage() {
  return <div className="admin-page"><PageHeader icon={Target} eyebrow={bi('Coach Portal · Programs', 'بوابة المدرب · البرامج')} title={bi('Assigned Programs', 'البرامج المكلف بها')} description={bi('Connect training objectives to the groups currently in your coaching scope.', 'اربط أهداف التدريب بالمجموعات الموجودة ضمن نطاقك التدريبي.')} actions={<PreviewNotice />} /><div className="portal-card-grid">{portalPrograms.slice(0, 4).map(program => <article className="portal-card" key={program.id}><span className="portal-card-icon"><Target size={18} /></span><h3><BilingualText value={program.name} /></h3><p><BilingualText value={program.focus} /></p><div className="program-pill-list">{program.pillars.map(pillar => <span key={pillar.en}><BilingualText value={pillar} /></span>)}</div><PortalStatus label={bi('Preview assignment', 'تكليف تجريبي')} tone="neutral" /></article>)}</div><PortalPreviewCard title={bi('Program plan preview', 'معاينة خطة البرنامج')} description={bi('Drills and objectives are presented from local reference data only.', 'يتم عرض التدريبات والأهداف من بيانات مرجعية محلية فقط.')} /></div>;
}

export function CoachPortalMessagesPage() {
  const [messages, setMessages] = useState([{ id: 'coach-message-1', from: bi('Parent Preview 01', 'ولي أمر تجريبي 01'), body: bi('Can we review the next training focus?', 'هل يمكننا مراجعة التركيز التدريبي القادم؟') }]);
  const [draft, setDraft] = useState('');
  const send = () => { if (!draft.trim()) return; setMessages(current => [...current, { id: `coach-message-${current.length + 1}`, from: bi('Coach · Local preview', 'المدرب · معاينة محلية'), body: bi(draft, draft) }]); setDraft(''); };
  return <div className="admin-page"><PageHeader icon={MessageCircle} eyebrow={bi('Coach Portal · Messages', 'بوابة المدرب · الرسائل')} title={bi('Coach Inbox', 'صندوق المدرب')} description={bi('A conversation workspace for local preview replies with no delivery claim.', 'مساحة محادثة للردود التجريبية المحلية دون ادعاء التسليم.')} actions={<PreviewNotice />} /><PortalSection title={bi('Conversation', 'المحادثة')} description={bi('Keep family context close to the training plan.', 'حافظ على سياق الأسرة قريبًا من خطة التدريب.') }><div className="message-thread">{messages.map(message => <article className="message-bubble" key={message.id}><strong><BilingualText value={message.from} /></strong><p><BilingualText value={message.body} /></p></article>)}</div><div className="portal-composer"><textarea value={draft} onChange={event => setDraft(event.target.value)} rows={3} placeholder="Write local preview reply | اكتب ردًا تجريبيًا محليًا" /><UiButton type="button" variant="primary" onClick={send}><Send size={14} /><BilingualText value={bi('Append reply', 'إضافة الرد')} /></UiButton></div></PortalSection></div>;
}

export function CoachPortalProfilePage() {
  const [notice, setNotice] = useState(false);
  return <div className="admin-page"><PageHeader icon={UserRound} eyebrow={bi('Coach Portal · Profile', 'بوابة المدرب · الملف الشخصي')} title={bi('Coach Profile', 'ملف المدرب')} description={bi('Review coaching scope, sports and local preferences.', 'راجع نطاق التدريب والرياضات والتفضيلات المحلية.')} actions={<PreviewNotice />} /><section className="portal-profile-hero"><span className="portal-card-icon"><UserRound size={25} /></span><div><h2>{activeCoach.nameEn}</h2><p lang="ar" dir="rtl">{activeCoach.nameAr}</p><EnterpriseStatus label={bi('Active preview', 'معاينة نشطة')} tone="active" /></div></section><PortalSection title={bi('Coaching scope', 'نطاق التدريب')}><div className="portal-metric-grid"><PortalMetric label={bi('Sports', 'الرياضات')} value={activeCoach.sportIds.length} /><PortalMetric label={bi('Groups', 'المجموعات')} value={activeCoach.groupIds.length} tone="green" /><PortalMetric label={bi('Players', 'اللاعبون')} value={portalCoachPlayers.length} tone="blue" /><PortalMetric label={bi('Specializations', 'التخصصات')} value={activeCoach.specializations.length} tone="gold" /></div></PortalSection><PortalSection title={bi('Profile note', 'ملاحظة الملف')} description={bi('This reference keeps profile changes local and transparent.', 'تحافظ هذه النسخة المرجعية على تغييرات الملف محلية وشفافة.')}><textarea className="portal-note-field" defaultValue="Preview coaching workspace" /><div className="dialog-actions"><UiButton type="button" variant="primary" onClick={() => setNotice(true)}><CheckCircle2 size={14} /><BilingualText value={bi('Apply locally', 'تطبيق محليًا')} /></UiButton></div></PortalSection>{notice && <div className="preview-notice" role="status"><BilingualText value={bi('Coach profile note updated locally', 'تم تحديث ملاحظة ملف المدرب محليًا')} /></div>}</div>;
}

export function CoachPortalPlayerDetailPage() {
  const { playerId } = useParams();
  const player = demoPlayers.find(item => item.id === playerId) ?? portalCoachPlayers[0];
  const metrics = getLatestPlayerMetrics(player.id);
  return <div className="admin-page"><PageHeader icon={UserRound} eyebrow={bi('Coach Portal · Athlete Detail', 'بوابة المدرب · تفاصيل الرياضي')} title={bi('Athlete Record', 'سجل الرياضي')} description={bi('A focused coaching view of the selected preview athlete.', 'عرض تدريبي مركز للرياضي التجريبي المحدد.')} actions={<PreviewNotice />} /><section className="portal-profile-hero"><span className="portal-card-icon"><UserRound size={25} /></span><div><h2>{player.nameEn}</h2><p lang="ar" dir="rtl">{player.nameAr}</p><small>{player.id} · {getSport(player.sportId)?.name.en}</small></div><EnterpriseStatus label={bi('Assigned', 'مكلف')} tone="active" /></section><section className="portal-metric-grid"><PortalMetric label={bi('Attendance', 'الحضور')} value={`${Math.round(((player.attendanceSummary?.attended ?? 0) / Math.max(player.attendanceSummary?.scheduled ?? 1, 1)) * 100)}%`} /><PortalMetric label={bi('Performance', 'الأداء')} value={`${getPlayerOverall(player.id)}/100`} tone="green" /><PortalMetric label={bi('Metric coverage', 'تغطية المؤشرات')} value={metrics.length} tone="blue" /><PortalMetric label={bi('Feedback notes', 'ملاحظات التغذية')} value={player.coachFeedback.length} tone="gold" /></section><PortalSection title={bi('Skill breakdown', 'تفصيل المهارات')}><div className="portal-list">{metrics.map(metric => <div className="portal-list-item" key={metric.definition.id}><div><strong><BilingualText value={metric.definition.name} /></strong><small><BilingualText value={getSport(player.sportId)?.name ?? bi('Sport', 'الرياضة')} /></small></div><EnterpriseProgress value={metric.current?.value ?? 0} /></div>)}</div></PortalSection><Link className="admin-link-button" to="/coach/players"><BilingualText value={bi('Back to coach roster', 'العودة إلى قائمة المدرب')} /></Link></div>;
}

export function CoachPortalGroupDetailPage() {
  const { groupId } = useParams();
  const group = getGroup(groupId) ?? portalGroups[0];
  const players = demoPlayers.filter(player => player.groupId === group.id);
  return <div className="admin-page"><PageHeader icon={UsersRound} eyebrow={bi('Coach Portal · Group Detail', 'بوابة المدرب · تفاصيل المجموعة')} title={group.name} description={bi('An operational group workspace connecting roster, sport and next sessions.', 'مساحة تشغيلية للمجموعة تربط القائمة والرياضة والحصص القادمة.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Players', 'اللاعبون')} value={players.length} /><PortalMetric label={bi('Capacity signal', 'مؤشر السعة')} value={`${Math.min(100, players.length * 20)}%`} tone="green" /><PortalMetric label={bi('Level', 'المستوى')} value={group.level.en} tone="blue" /><PortalMetric label={bi('Sport', 'الرياضة')} value={getSport(group.sportId)?.name.en ?? group.sportId} tone="gold" /></section><PortalSection title={bi('Group roster', 'قائمة المجموعة')}><EnterpriseTable caption={bi('Group roster table', 'جدول قائمة المجموعة')}><thead><tr>{[bi('Player', 'اللاعب'), bi('Attendance', 'الحضور'), bi('Performance', 'الأداء'), bi('Next action', 'الإجراء القادم')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{players.map(player => <tr key={player.id}><td><strong><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></strong></td><td>{player.attendanceSummary?.attended ?? 0}/{player.attendanceSummary?.scheduled ?? 0}</td><td>{getPlayerOverall(player.id)}/100</td><td><Link className="admin-link-button" to={`/coach/players/${player.id}`}><BilingualText value={bi('Review', 'مراجعة')} /></Link></td></tr>)}</tbody></EnterpriseTable></PortalSection><PortalPreviewCard title={bi('Group workspace boundary', 'حدود مساحة المجموعة')} description={bi('Roster and session changes remain local preview interactions until a verified service is connected.', 'تبقى تغييرات القائمة والحصص تفاعلات معاينة محلية حتى ربط خدمة موثقة.')} /></div>;
}
