import { Activity, ArrowLeft, CalendarDays, CheckCircle2, UserRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseProgress, EnterpriseStatus, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalMetric, PortalSection } from '../../../components/portal/PortalUI';
import { getGroup, getPlayer, getPlayerOverall, getSport } from '../../../data/demo/selectors';
import { portalChildren } from '../portalData';

export function ParentPortalChildDetailPage() {
  const { childId } = useParams();
  const child = getPlayer(childId) ?? portalChildren[0];
  const attendance = child.attendanceSummary ?? { attended: 0, scheduled: 0 };
  const rate = Math.round(attendance.attended / Math.max(attendance.scheduled, 1) * 100);
  return <div className="admin-page"><PageHeader icon={UserRound} eyebrow={bi('Parent Portal · Child Detail', 'بوابة ولي الأمر · تفاصيل الطفل')} title={{ en: child.nameEn, ar: child.nameAr }} description={bi('A family-safe athlete record connected to sport, group and progress context.', 'سجل رياضي آمن للأسرة مرتبط بسياق الرياضة والمجموعة والتقدم.')} actions={<PreviewNotice />} /><section className="portal-profile-hero"><span className="portal-card-icon"><UserRound size={24} /></span><div><h2>{child.nameEn}</h2><p lang="ar" dir="rtl">{child.nameAr}</p><small>{child.id} · {getSport(child.sportId)?.name.en}</small></div><EnterpriseStatus label={bi('Linked child', 'طفل مرتبط')} tone="active" /></section><section className="portal-metric-grid"><PortalMetric label={bi('Attendance', 'الحضور')} value={`${rate}%`} tone="green" /><PortalMetric label={bi('Performance', 'الأداء')} value={`${getPlayerOverall(child.id)}/100`} /><PortalMetric label={bi('Age', 'العمر')} value={child.age ?? '—'} tone="blue" /><PortalMetric label={bi('Feedback notes', 'ملاحظات التدريب')} value={child.coachFeedback.length} tone="gold" /></section><section className="enterprise-grid-2"><PortalSection title={bi('Training context', 'سياق التدريب')}><div className="portal-list"><div className="portal-list-item"><div><strong><BilingualText value={bi('Sport', 'الرياضة')} /></strong><small><BilingualText value={getSport(child.sportId)?.name ?? bi('Not assigned', 'غير معين')} /></small></div><Activity size={16} /></div><div className="portal-list-item"><div><strong><BilingualText value={bi('Group', 'المجموعة')} /></strong><small><BilingualText value={getGroup(child.groupId)?.name ?? bi('Not assigned', 'غير معين')} /></small></div><CalendarDays size={16} /></div></div></PortalSection><PortalSection title={bi('Progress signal', 'مؤشر التقدم')}><EnterpriseProgress value={getPlayerOverall(child.id)} label={bi('Sport-aware performance', 'الأداء الخاص بالرياضة')} color="green" /><div style={{ marginTop: 18 }}><EnterpriseProgress value={rate} label={bi('Attendance consistency', 'انتظام الحضور')} color="blue" /></div></PortalSection></section><Link className="admin-link-button" to="/parent/children"><ArrowLeft size={14} /><BilingualText value={bi('Back to children', 'العودة إلى الأبناء')} /></Link><div className="preview-notice"><CheckCircle2 size={15} /><BilingualText value={bi('This family record is derived from preview fixtures and is not a live child account.', 'هذا السجل الأسري مشتق من بيانات تجريبية وليس حساب طفل مباشر.')} /></div></div>;
}
