import { Activity, CalendarDays, CheckCircle2, CreditCard, FileQuestion, FileText, Inbox, MessageCircle, ShieldCheck, TrendingUp, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import {
  childLabel,
  getActiveParent,
  getChildPerformance,
  getFamilyPayments,
  getFamilySessions,
  getFamilySubscriptions,
  getLinkedChildren,
  getSport,
} from '../../../portals/parent/parentData';

export function ParentPortalSchedulePage() {
  const children = getLinkedChildren();
  const rows = getFamilySessions(children);
  const now = Date.now();
  const upcoming = rows.filter(({ session }) => new Date(session.startsAt).getTime() >= now);
  const past = rows.filter(({ session }) => new Date(session.startsAt).getTime() < now);
  return <div className="parent-page"><Hero icon={<CalendarDays size={18} />} kicker={bi('Family Training Calendar', 'تقويم تدريبات الأسرة')} title={bi('Schedule', 'الجدول')} description={bi('Only sessions linked through the current children training groups are shown.', 'يتم عرض الحصص المرتبطة فقط من خلال المجموعات التدريبية الحالية للأبناء.')} metrics={[['Linked children','الأبناء المرتبطون',String(children.length),''],['Upcoming','القادمة',String(upcoming.length),'green'],['Past records','السجلات السابقة',String(past.length),''],['Sports','الرياضات',String(new Set(children.map(c=>c.sportId)).size),'gold']]} />
    <Panel title={bi('Upcoming sessions', 'الحصص القادمة')} description={bi('Session dates and statuses come from linked training records.', 'تواريخ الحصص وحالاتها تأتي من سجلات التدريب المرتبطة.')}>
      {upcoming.length ? <div className="parent-list">{upcoming.map(({session,child}) => <SessionRow key={session.id} session={session} child={child} />)}</div> : <Empty icon={<CalendarDays />} title={bi('No upcoming sessions', 'لا توجد حصص قادمة')} description={bi('The family calendar remains empty until a future session is linked to a child training group.', 'يظل تقويم الأسرة فارغًا حتى يتم ربط حصة مستقبلية بمجموعة تدريب أحد الأبناء.')} />}
    </Panel>
    {past.length > 0 && <Panel title={bi('Past session records', 'سجلات الحصص السابقة')}><div className="parent-list">{past.slice().reverse().map(({session,child}) => <SessionRow key={session.id} session={session} child={child} />)}</div></Panel>}
  </div>;
}

export function ParentPortalPerformancePage() {
  const children = getLinkedChildren();
  const recorded = children.map(child => ({ child, ...getChildPerformance(child) })).filter(item => item.metrics.length > 0);
  const average = recorded.length ? Math.round(recorded.reduce((sum,item)=>sum+(item.score ?? 0),0)/recorded.length) : null;
  return <div className="parent-page"><Hero icon={<TrendingUp size={18} />} kicker={bi('Recorded Development', 'التطور المسجل')} title={bi('Children Performance', 'أداء الأبناء')} description={bi('Performance is calculated only from metrics that actually have current records. Missing metrics never become zero.', 'يتم حساب الأداء فقط من المؤشرات التي لديها سجلات حالية فعلية. ولا تتحول المؤشرات المفقودة إلى صفر.')} metrics={[['Children with metrics','أبناء لديهم مؤشرات',String(recorded.length),''],['Family signal','مؤشر الأسرة',average===null?'Not recorded':`${average}/100`,average===null?'':'gold'],['Linked children','الأبناء المرتبطون',String(children.length),''],['Sports','الرياضات',String(new Set(children.map(c=>c.sportId)).size),'green']]} />
    {recorded.length ? <div className="parent-grid-2">{recorded.map(({child,metrics,score}) => <article className="parent-panel" key={child.id}><div className="parent-card-head"><Avatar name={child.nameEn}/><div><h2>{child.nameEn}</h2><small lang="ar" dir="rtl">{child.nameAr}</small></div><span className="parent-scope" style={{marginInlineStart:'auto'}}>{score ?? '—'}/100</span></div><p style={{fontSize:11,color:'#94a3b8'}}><BilingualText value={getSport(child.sportId)?.name ?? bi('Sport not assigned','الرياضة غير معينة')} /></p><div className="parent-list">{metrics.map(metric => <div className="parent-list-row" key={metric.definition.id}><div><strong><BilingualText value={metric.definition.name} /></strong><small>{metric.current?.recordedAt ?? ''}</small></div><strong style={{color:'#f0cf67'}}>{metric.current?.value}{metric.definition.unit ? <> <BilingualText value={metric.definition.unit}/></> : null}</strong></div>)}</div></article>)}</div> : <Empty icon={<Activity/>} title={bi('No performance metrics recorded', 'لا توجد مؤشرات أداء مسجلة')} description={bi('Performance cards and family averages stay unset until real metric records exist for linked children.', 'تظل بطاقات الأداء ومتوسط الأسرة غير محددة حتى تتوفر سجلات قياس فعلية للأبناء المرتبطين.')} />}
  </div>;
}

export function ParentPortalFeedbackPage() {
  const children = getLinkedChildren();
  const notes = children.flatMap(child => (child.coachFeedback ?? []).map(note => ({ child, note }))).sort((a,b)=>b.note.createdAt.localeCompare(a.note.createdAt));
  return <div className="parent-page"><Hero icon={<MessageCircle size={18}/>} kicker={bi('Recorded Coaching Notes','ملاحظات التدريب المسجلة')} title={bi('Coach Feedback','ملاحظات المدرب')} description={bi('This view exposes only coaching notes already attached to linked player records.', 'يعرض هذا القسم فقط ملاحظات التدريب المرتبطة بالفعل بسجلات اللاعبين المرتبطين.')} metrics={[['Linked children','الأبناء المرتبطون',String(children.length),''],['Recorded notes','الملاحظات المسجلة',String(notes.length),'gold'],['Strength items','نقاط القوة',String(notes.reduce((sum,x)=>sum+x.note.strengths.length,0)),'green'],['Focus items','محاور التطوير',String(notes.reduce((sum,x)=>sum+x.note.focusAreas.length,0)),'']]} />
    <Panel title={bi('Family feedback timeline','سجل ملاحظات الأسرة')} description={bi('No message delivery or coach response is implied by these records.', 'لا تعني هذه السجلات وجود إرسال رسائل أو رد مباشر من المدرب.')}>
      {notes.length ? <div className="parent-list">{notes.map(({child,note}) => <article className="parent-card" key={note.id}><div className="parent-card-head"><Avatar name={child.nameEn}/><div><h3>{child.nameEn}</h3><small>{note.createdAt}</small></div><span className="parent-status neutral" style={{marginInlineStart:'auto'}}><BilingualText value={bi('Recorded','مسجل')}/></span></div><p><BilingualText value={note.summary}/></p><div className="parent-actions">{note.strengths.map(item=><span className="parent-status good" key={item.en}><BilingualText value={item}/></span>)}{note.focusAreas.map(item=><span className="parent-status warn" key={item.en}><BilingualText value={item}/></span>)}</div></article>)}</div> : <Empty icon={<MessageCircle/>} title={bi('No coach notes recorded','لا توجد ملاحظات مدرب مسجلة')} description={bi('The page will populate when a feedback record is attached to a linked child.','ستمتلئ الصفحة عند ربط سجل ملاحظات بأحد الأبناء المرتبطين.')} />}
    </Panel>
  </div>;
}

export function ParentPortalPaymentsPage() {
  const children = getLinkedChildren();
  const payments = getFamilyPayments(children);
  const completed = payments.filter(p=>p.status==='completed');
  const pending = payments.filter(p=>p.status==='pending');
  return <div className="parent-page"><Hero icon={<CreditCard size={18}/>} kicker={bi('Linked Billing Records','سجلات الدفع المرتبطة')} title={bi('Payments','المدفوعات')} description={bi('This is a preview ledger of existing linked records. It does not process payments, calculate an outstanding balance, or invent invoices.', 'هذا دفتر معاينة للسجلات المرتبطة الموجودة. لا يعالج المدفوعات ولا يحسب رصيدًا مستحقًا ولا ينشئ فواتير مختلقة.')} metrics={[['Records','السجلات',String(payments.length),''],['Completed','المكتملة',String(completed.length),'green'],['Pending','قيد الانتظار',String(pending.length),'gold'],['Linked children','الأبناء المرتبطون',String(new Set(payments.map(p=>p.playerId)).size),'']]} />
    <Panel title={bi('Payment records','سجلات الدفع')} description={bi('References and statuses are shown exactly when present in the preview finance dataset.', 'يتم عرض المراجع والحالات كما هي فقط عند وجودها في بيانات المالية التجريبية.')}>
      {payments.length ? <div className="parent-table-wrap"><table className="parent-table"><thead><tr>{[bi('Child','الابن'),bi('Amount','المبلغ'),bi('Method','الطريقة'),bi('Date','التاريخ'),bi('Reference','المرجع'),bi('Status','الحالة')].map(x=><th key={x.en}><BilingualText value={x}/></th>)}</tr></thead><tbody>{payments.map(payment=>{const child=children.find(c=>c.id===payment.playerId);return <tr key={payment.id}><td>{child?`${child.nameEn} · ${child.nameAr}`:payment.playerId}</td><td><strong>{payment.amount} {payment.currency}</strong></td><td><BilingualText value={payment.method}/></td><td>{payment.paidAt}</td><td>{payment.reference ?? <Missing/>}</td><td><Status value={payment.status}/></td></tr>})}</tbody></table></div> : <Empty icon={<CreditCard/>} title={bi('No linked payment records','لا توجد سجلات دفع مرتبطة')} description={bi('No amount, invoice or balance is inferred from an empty ledger.','لا يتم استنتاج أي مبلغ أو فاتورة أو رصيد من دفتر فارغ.')} />}
    </Panel>
  </div>;
}

export function ParentPortalSubscriptionsPage() {
  const children = getLinkedChildren();
  const rows = getFamilySubscriptions(children);
  return <div className="parent-page"><Hero icon={<ShieldCheck size={18}/>} kicker={bi('Membership Records','سجلات العضوية')} title={bi('Subscriptions','الاشتراكات')} description={bi('Membership rows are shown only when an existing subscription record is linked to a child.', 'تظهر سجلات العضوية فقط عند وجود اشتراك مرتبط بأحد الأبناء.')} metrics={[['Subscriptions','الاشتراكات',String(rows.length),''],['Active','النشطة',String(rows.filter(r=>r.status==='active').length),'green'],['Pending','قيد الانتظار',String(rows.filter(r=>r.status==='pending').length),'gold'],['Children covered','الأبناء المشمولون',String(new Set(rows.map(r=>r.playerId)).size),'']]} />
    {rows.length ? <div className="parent-grid-2">{rows.map(row=>{const child=children.find(c=>c.id===row.playerId);return <article className="parent-panel" key={row.id}><div className="parent-panel-head"><div><span className="parent-kicker"><BilingualText value={bi('Membership','عضوية')}/></span><h2><BilingualText value={row.plan}/></h2></div><Status value={row.status}/></div><div className="parent-field-grid" style={{marginTop:14}}><Field label={bi('Child','الابن')} value={child?`${child.nameEn} · ${child.nameAr}`:row.playerId}/><Field label={bi('Amount','المبلغ')} value={`${row.amount} ${row.currency}`}/><Field label={bi('Start date','تاريخ البداية')} value={row.startDate}/><Field label={bi('End date','تاريخ النهاية')} value={row.endDate}/><Field label={bi('Program ID','معرف البرنامج')} value={row.programId}/><Field label={bi('Branch ID','معرف الفرع')} value={row.branchId}/></div><div className="parent-truth" style={{marginTop:14}}><ShieldCheck size={13}/><BilingualText value={bi('Renewal and charging actions are unavailable because no billing backend is connected here.','إجراءات التجديد والخصم غير متاحة لعدم ربط نظام دفع خلفي هنا.')}/></div></article>})}</div> : <Empty icon={<ShieldCheck/>} title={bi('No subscription records','لا توجد سجلات اشتراك')} description={bi('Membership status remains unrecorded until a subscription is linked.','تظل حالة العضوية غير مسجلة حتى يتم ربط اشتراك.')} />}
  </div>;
}

export function ParentPortalDocumentsPage() {
  return <div className="parent-page"><Hero icon={<FileText size={18}/>} kicker={bi('Family Document Vault','خزنة مستندات الأسرة')} title={bi('Documents','المستندات')} description={bi('The document workspace is ready, but no child-linked document storage or download source is connected in the current repository.', 'مساحة المستندات جاهزة، لكن لا يوجد حاليًا تخزين أو مصدر تنزيل لمستندات مرتبطة بالأبناء في المستودع.')} metrics={[['Linked documents','المستندات المرتبطة','Not recorded',''],['Upload service','خدمة الرفع','Unavailable',''],['Download source','مصدر التنزيل','Unavailable',''],['Storage','التخزين','Not connected','']]} />
    <Panel title={bi('Document repository','مستودع المستندات')}><Empty icon={<FileQuestion/>} title={bi('No child-linked documents are connected','لا توجد مستندات مرتبطة بالأبناء')} description={bi('Identity files, consents, medical clearances and certificates will appear here only after a real document record and storage object are connected.', 'ستظهر ملفات الهوية والموافقات والفحوص والشهادات هنا فقط بعد ربط سجل مستند وملف تخزين حقيقي.')} /></Panel>
  </div>;
}

export function ParentPortalMessagesPage() {
  return <div className="parent-page"><Hero icon={<MessageCircle size={18}/>} kicker={bi('Family Communications','تواصل الأسرة')} title={bi('Messages','الرسائل')} description={bi('The communication UI is present, while message history and delivery remain disabled until a secure messaging backend is connected.', 'واجهة التواصل موجودة، بينما يظل سجل الرسائل والإرسال معطلين حتى يتم ربط خدمة مراسلة آمنة.')} metrics={[['Threads','المحادثات','Not recorded',''],['Unread','غير المقروء','Not recorded',''],['Delivery','الإرسال','Unavailable',''],['Backend','الخدمة الخلفية','Not connected','']]} />
    <section className="parent-panel" style={{minHeight:430,display:'grid',gridTemplateRows:'auto 1fr auto'}}><div className="parent-panel-head"><div><h2><BilingualText value={bi('Secure family conversation','محادثة الأسرة الآمنة')}/></h2><p><BilingualText value={bi('No fabricated coach thread is shown.','لا يتم عرض محادثة مدرب مختلقة.')}/></p></div><span className="parent-status neutral"><BilingualText value={bi('Offline','غير متصل')}/></span></div><Empty icon={<Inbox/>} title={bi('Messaging is not connected yet','خدمة الرسائل غير متصلة بعد')} description={bi('Conversation history will appear only when a real thread source is connected to this parent account.','سيظهر سجل المحادثات فقط عند ربط مصدر محادثات حقيقي بحساب ولي الأمر.')}/><div className="parent-actions" style={{paddingTop:14,borderTop:'1px solid rgba(255,255,255,.08)'}}><input disabled aria-label="Message composer unavailable | محرر الرسائل غير متاح" placeholder="Messaging unavailable / الرسائل غير متاحة" style={{flex:1,minHeight:42,borderRadius:12,border:'1px solid rgba(255,255,255,.08)',background:'rgba(255,255,255,.025)',padding:'0 12px',color:'#64748b'}}/><button type="button" disabled className="parent-secondary-action"><BilingualText value={bi('Send unavailable','الإرسال غير متاح')}/></button></div></section>
  </div>;
}

export function ParentPortalProfilePage() {
  const parent = getActiveParent();
  const children = getLinkedChildren(parent);
  if (!parent) return <Empty icon={<UserRound/>} title={bi('Parent profile unavailable','ملف ولي الأمر غير متاح')} description={bi('No valid parent session record could be resolved.','تعذر العثور على سجل صالح لجلسة ولي الأمر.')}/>;
  const phone = valid(parent.phone); const email = valid(parent.email);
  return <div className="parent-page"><Hero icon={<UserRound size={18}/>} kicker={bi('Family Identity','هوية الأسرة')} title={{en:parent.nameEn,ar:parent.nameAr}} description={bi('Account identity and linked-child relationships are shown from the current preview parent record only.', 'يتم عرض هوية الحساب وعلاقات الأبناء المرتبطين من سجل ولي الأمر التجريبي الحالي فقط.')} metrics={[['Parent ID','معرف ولي الأمر',parent.id,''],['Linked children','الأبناء المرتبطون',String(children.length),'green'],['Preferred language','اللغة المفضلة',parent.preferredLanguage.toUpperCase(),'gold'],['Status','الحالة',parent.status,'']]} />
    <div className="parent-grid-2"><Panel title={bi('Account record','سجل الحساب')}><div className="parent-field-grid"><Field label={bi('English name','الاسم بالإنجليزية')} value={parent.nameEn}/><Field label={bi('Arabic name','الاسم بالعربية')} value={parent.nameAr}/><Field label={bi('Phone','الهاتف')} value={phone}/><Field label={bi('Email','البريد الإلكتروني')} value={email}/><Field label={bi('Preferred language','اللغة المفضلة')} value={parent.preferredLanguage}/><Field label={bi('Account status','حالة الحساب')} value={parent.status}/></div><div className="parent-truth" style={{marginTop:14}}><ShieldCheck size={13}/><BilingualText value={bi('Placeholder phone and email values are treated as unavailable, not as real contact details.','يتم التعامل مع قيم الهاتف والبريد المؤقتة كبيانات غير متاحة وليست بيانات تواصل حقيقية.')}/></div></Panel><Panel title={bi('Linked athletes','اللاعبون المرتبطون')}><div className="parent-list">{children.map(child=><Link to={`/parent/children/${child.id}`} className="parent-list-row" key={child.id} style={{textDecoration:'none'}}><div><strong>{child.nameEn}</strong><small lang="ar" dir="rtl">{child.nameAr}</small></div><span className="parent-status good"><BilingualText value={bi('Linked','مرتبط')}/></span></Link>)}</div></Panel></div>
  </div>;
}

function Hero({icon,kicker,title,description,metrics}:{icon:React.ReactNode;kicker:{en:string;ar:string};title:{en:string;ar:string};description:{en:string;ar:string};metrics:Array<[string,string,string,string]>}) { return <section className="parent-hero"><div className="parent-hero-row"><div><span className="parent-kicker">{icon}<BilingualText value={kicker}/></span><h1><BilingualText value={title}/></h1><p><BilingualText value={description}/></p></div><span className="parent-scope"><ShieldCheck size={12}/><BilingualText value={bi('Family preview records','سجلات معاينة الأسرة')}/></span></div><div className="parent-metrics">{metrics.map(([en,ar,value,tone])=><div className="parent-metric" key={en}><span><BilingualText value={bi(en,ar)}/></span><strong className={tone}>{value}</strong></div>)}</div></section> }
function Panel({title,description,children}:{title:{en:string;ar:string};description?:{en:string;ar:string};children:React.ReactNode}) { return <section className="parent-panel"><div className="parent-panel-head"><div><h2><BilingualText value={title}/></h2>{description&&<p><BilingualText value={description}/></p>}</div></div><div style={{marginTop:14}}>{children}</div></section> }
function Empty({icon,title,description}:{icon:React.ReactNode;title:{en:string;ar:string};description:{en:string;ar:string}}){return <div className="parent-empty"><div>{icon}<h3><BilingualText value={title}/></h3><p><BilingualText value={description}/></p></div></div>}
function Avatar({name}:{name:string}){return <span className="parent-avatar">{name.charAt(0).toUpperCase()}</span>}
function Field({label,value}:{label:{en:string;ar:string};value?:string|number}){return <div className="parent-field"><span><BilingualText value={label}/></span><strong className={value===undefined?'missing':''}>{value===undefined?<BilingualText value={bi('Not recorded','غير مسجل')}/>:value}</strong></div>}
function Missing(){return <span style={{color:'#667085',fontStyle:'italic'}}><BilingualText value={bi('Not recorded','غير مسجل')}/></span>}
function valid(value?:string){return value && value.trim() && value.trim()!=='-' ? value : undefined}
function Status({value}:{value:string}){const tone=value==='active'||value==='completed'?'good':value==='pending'?'warn':'neutral';return <span className={`parent-status ${tone}`}><BilingualText value={bi(value,value==='active'?'نشط':value==='completed'?'مكتمل':value==='pending'?'قيد الانتظار':value==='expired'?'منتهٍ':value==='failed'?'فشل':value)}/></span>}
function SessionRow({session,child}:{session:{id:string;startsAt:string;status:{en:string;ar:string};sportId:string};child:{id:string;nameEn:string;nameAr:string}}){const date=new Date(session.startsAt);const when=Number.isNaN(date.getTime())?session.startsAt:`${date.toLocaleString('en',{dateStyle:'medium',timeStyle:'short'})} · ${date.toLocaleString('ar',{dateStyle:'medium',timeStyle:'short'})}`;return <div className="parent-list-row"><div><strong><BilingualText value={getSport(session.sportId)?.name ?? bi('Training session','حصة تدريبية')}/></strong><small>{when}</small><small>{child.nameEn} · {child.nameAr}</small></div><Status value={session.status.en.toLowerCase()}/></div>}
