import { Activity, ArrowLeft, CalendarDays, CheckCircle2, MessageCircle, ShieldCheck, UserRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { getChildAttendance, getChildPerformance, getGroup, getLinkedChildren, getSport } from '../../../portals/parent/parentData';

export function ParentPortalChildDetailPage(){
  const {childId}=useParams<{childId:string}>();
  const child=getLinkedChildren().find(item=>item.id===childId);
  if(!child)return <div className="parent-page"><div className="parent-empty"><div><UserRound/><h3><BilingualText value={bi('Linked child not found','لم يتم العثور على الابن المرتبط')}/></h3><p><BilingualText value={bi('This route does not match a player linked to the active parent session.','هذا المسار لا يطابق لاعبًا مرتبطًا بجلسة ولي الأمر النشطة.')}/></p><Link className="parent-primary-action" to="/parent/children" style={{marginTop:14}}><ArrowLeft size={14} className="rtl:rotate-180"/><BilingualText value={bi('Back to children','العودة إلى الأبناء')}/></Link></div></div></div>;
  const attendance=getChildAttendance(child);
  const performance=getChildPerformance(child);
  const group=getGroup(child.groupId);
  const sport=getSport(child.sportId);

  return <div className="parent-page"><section className="parent-hero"><div className="parent-hero-row"><div><span className="parent-kicker"><UserRound size={18}/><BilingualText value={bi('Linked Athlete Record','سجل اللاعب المرتبط')}/></span><h1>{child.nameEn}<span lang="ar" dir="rtl"> · {child.nameAr}</span></h1><p><BilingualText value={bi('A parent-scoped view of identity, assignments, attendance, recorded development and coaching notes.','عرض مخصص لولي الأمر للهوية والتعيينات والحضور والتطور المسجل وملاحظات التدريب.')}/></p></div><span className="parent-scope"><ShieldCheck size={12}/>{child.id}</span></div><div className="parent-metrics"><Metric label={bi('Attendance','الحضور')} value={attendance.rate===null?'Not recorded':`${attendance.rate}%`} tone="green"/><Metric label={bi('Performance','الأداء')} value={performance.score===null?'Not recorded':`${performance.score}/100`} tone="gold"/><Metric label={bi('Feedback notes','ملاحظات التدريب')} value={String(child.coachFeedback?.length??0)}/><Metric label={bi('Age','العمر')} value={typeof child.age==='number'?String(child.age):'Not recorded'}/></div></section>

    <div className="parent-grid-2"><section className="parent-panel"><div className="parent-panel-head"><div><h2><BilingualText value={bi('Athlete identity & assignment','هوية اللاعب والتعيين')}/></h2></div></div><div className="parent-field-grid" style={{marginTop:14}}><Field label={bi('English name','الاسم بالإنجليزية')} value={child.nameEn}/><Field label={bi('Arabic name','الاسم بالعربية')} value={child.nameAr}/><Field label={bi('Player ID','معرف اللاعب')} value={child.id}/><Field label={bi('Age','العمر')} value={child.age}/><Field label={bi('Date of birth','تاريخ الميلاد')} value={child.dateOfBirth}/><Field label={bi('Sport','الرياضة')} value={sport?`${sport.name.en} · ${sport.name.ar}`:undefined}/><Field label={bi('Training group','المجموعة التدريبية')} value={group?`${group.name.en} · ${group.name.ar}`:undefined}/><Field label={bi('Level','المستوى')} value={`${child.level.en} · ${child.level.ar}`}/></div></section>
      <section className="parent-panel"><div className="parent-panel-head"><div><h2><BilingualText value={bi('Recorded development','التطور المسجل')}/></h2><p><BilingualText value={bi('Only current metrics with records are displayed.','يتم عرض المؤشرات الحالية المسجلة فقط.')}/></p></div></div>{performance.metrics.length?<div className="parent-list" style={{marginTop:14}}>{performance.metrics.map(metric=><div className="parent-list-row" key={metric.definition.id}><div><strong><BilingualText value={metric.definition.name}/></strong><small>{metric.current?.recordedAt??''}</small></div><strong style={{color:'#f0cf67'}}>{metric.current?.value}{metric.definition.unit?<> <BilingualText value={metric.definition.unit}/></>:null}</strong></div>)}</div>:<div className="parent-truth" style={{marginTop:14}}><Activity size={13}/><BilingualText value={bi('No performance metric is recorded for this child.','لا يوجد مؤشر أداء مسجل لهذا اللاعب.')}/></div>}</section></div>

    <div className="parent-grid-2"><section className="parent-panel"><div className="parent-panel-head"><div><h2><BilingualText value={bi('Attendance history','سجل الحضور')}/></h2></div><span className="parent-status good">{attendance.total}</span></div>{attendance.records.length?<div className="parent-list" style={{marginTop:14}}>{attendance.records.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(record=><div className="parent-list-row" key={record.id}><div><strong>{record.date}</strong><small><BilingualText value={bi('Training attendance record','سجل حضور تدريبي')}/></small></div><span className={`parent-status ${record.status==='present'?'good':record.status==='late'?'warn':'neutral'}`}><CheckCircle2 size={11}/>{record.status}</span></div>)}</div>:<div className="parent-truth" style={{marginTop:14}}><CalendarDays size={13}/><BilingualText value={bi('No attendance entries recorded.','لا توجد سجلات حضور مسجلة.')}/></div>}</section>
      <section className="parent-panel"><div className="parent-panel-head"><div><h2><BilingualText value={bi('Coach feedback records','سجلات ملاحظات المدرب')}/></h2></div></div>{child.coachFeedback?.length?<div className="parent-list" style={{marginTop:14}}>{[...child.coachFeedback].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(note=><article className="parent-card" key={note.id}><div className="parent-card-head"><MessageCircle size={16} style={{color:'#d4af37'}}/><div><h3>{note.createdAt}</h3></div></div><p><BilingualText value={note.summary}/></p><div className="parent-actions">{note.strengths.map(item=><span className="parent-status good" key={item.en}><BilingualText value={item}/></span>)}{note.focusAreas.map(item=><span className="parent-status warn" key={item.en}><BilingualText value={item}/></span>)}</div></article>)}</div>:<div className="parent-truth" style={{marginTop:14}}><MessageCircle size={13}/><BilingualText value={bi('No coaching feedback has been recorded.','لم يتم تسجيل ملاحظات تدريبية.')}/></div>}</section></div>

    <div className="parent-actions"><Link className="parent-secondary-action" to="/parent/children"><ArrowLeft size={14} className="rtl:rotate-180"/><BilingualText value={bi('Back to children','العودة إلى الأبناء')}/></Link><Link className="parent-secondary-action" to="/parent/schedule"><CalendarDays size={14}/><BilingualText value={bi('Family schedule','جدول الأسرة')}/></Link><Link className="parent-secondary-action" to="/parent/performance"><Activity size={14}/><BilingualText value={bi('Family performance','أداء الأسرة')}/></Link></div>
  </div>;
}
function Metric({label,value,tone='' }:{label:{en:string;ar:string};value:string;tone?:string}){return <div className="parent-metric"><span><BilingualText value={label}/></span><strong className={tone}>{value}</strong></div>}
function Field({label,value}:{label:{en:string;ar:string};value?:string|number}){return <div className="parent-field"><span><BilingualText value={label}/></span><strong className={value===undefined?'missing':''}>{value===undefined?<BilingualText value={bi('Not recorded','غير مسجل')}/>:value}</strong></div>}
