import { CalendarDays, CreditCard, HeartHandshake, MessageSquareText, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { demoParents } from '../../../data/demo/parents';
import { getPlayer, getSport } from '../../../data/demo/selectors';

export function ParentPortalOverviewPage() {
  const parent = demoParents[0]; const children = parent.playerIds.map(getPlayer).filter(Boolean);
  const attended = children.reduce((sum, player) => sum + (player?.attendanceSummary?.attended ?? 0), 0);
  const scheduled = children.reduce((sum, player) => sum + (player?.attendanceSummary?.scheduled ?? 0), 0);
  return <div className="admin-page"><PageHeader eyebrow={bi('Parent Portal', 'بوابة ولي الأمر')} title={bi('Family Overview', 'نظرة عامة للأسرة')} description={bi('Children, attendance and communication context in one truthful preview workspace.', 'سياق الأبناء والحضور والتواصل في مساحة معاينة صادقة واحدة.')} />
    <section className="portal-overview-hero parent-family-hero"><article className="portal-overview-primary parent-family-card"><span className="parent-family-icon"><HeartHandshake /></span><div className="parent-family-body"><h2 className="parent-family-title">{parent.nameEn}<span lang="ar" dir="rtl" className="parent-family-sub"> · {parent.nameAr}</span></h2><p className="parent-family-desc"><BilingualText value={bi('A calm family workspace. All linked athletes, attendance context and communication previews are truthful and sourced from existing records only.', 'مساحة عمل أسرية هادئة. جميع الرياضيين المرتبطين وسياق الحضور ومعاينات التواصل صادقة ومأخوذة من السجلات الموجودة فقط.')} /></p></div></article><article className="portal-overview-score parent-family-stats"><div className="parent-stat-row"><small><BilingualText value={bi('Linked Children', 'الأبناء المرتبطون')} /></small><strong>{children.length}</strong></div><div className="parent-stat-divider" /><div className="parent-stat-row"><small><BilingualText value={bi('Attendance Context', 'سياق الحضور')} /></small><strong>{attended}/{scheduled}</strong></div></article></section>
    <section className="portal-action-grid parent-action-grid"><Link to="/parent/children" className="parent-action-card"><UsersRound /><span className="parent-action-label"><BilingualText value={bi('Children', 'الأبناء')} /></span><small><BilingualText value={bi('Review linked athlete profiles', 'مراجعة ملفات الرياضيين المرتبطين')} /></small></Link><Link to="/parent/schedule" className="parent-action-card"><CalendarDays /><span className="parent-action-label"><BilingualText value={bi('Family Schedule', 'جدول الأسرة')} /></span><small><BilingualText value={bi('Training context preview', 'معاينة سياق التدريب')} /></small></Link><Link to="/parent/messages" className="parent-action-card"><MessageSquareText /><span className="parent-action-label"><BilingualText value={bi('Messages', 'الرسائل')} /></span><small><BilingualText value={bi('Communication-ready preview state', 'حالة معاينة جاهزة للتواصل')} /></small></Link></section>
    <section className="portal-overview-list parent-family-list"><header><BilingualText value={bi('Children Snapshot', 'لمحة عن الأبناء')} /><UsersRound /></header><div className="parent-children-grid">{children.map(player => player && <article key={player.id} className="parent-child-card"><div className="parent-child-head"><span className="parent-child-avatar"><UsersRound size={16} /></span><div><strong className="parent-child-name">{player.nameEn}<span lang="ar" dir="rtl"> · {player.nameAr}</span></strong></div></div><div className="parent-child-stats"><span className="parent-child-stat"><BilingualText value={getSport(player.sportId)?.name ?? bi('Sport Preview', 'معاينة الرياضة')} /></span></div></article>)}</div><Link className="admin-link-button parent-payments-link" to="/parent/payments"><CreditCard /><BilingualText value={bi('Payments Preview', 'معاينة المدفوعات')} /></Link></section>
  </div>;
}
