import { CalendarDays, CheckCircle2, CreditCard, Download, FileText, HeartHandshake, MessageCircle, Send, ShieldCheck, TrendingUp, UserRound, UsersRound, WalletCards } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '../../../components/admin/AdminUI';
import { BilingualText, bi } from '../../../components/bilingual/BilingualText';
import { EnterpriseProgress, EnterpriseStatus, EnterpriseTable, PreviewNotice } from '../../../components/enterprise/EnterpriseUI';
import { PortalMetric, PortalPreviewCard, PortalSection, PortalStatus, PortalTrend } from '../../../components/portal/PortalUI';
import { getPlayerOverall, getSport } from '../../../data/demo/selectors';
import { activeParent, portalChildren, portalPrograms, portalSessions, previewDocuments, previewPayments, previewSubscriptions } from '../portalData';
import { UiButton } from '../../../components/ui/UiPrimitives';

const childFor = (id: string) => portalChildren.find(child => child.id === id);

export function ParentPortalSchedulePage() {
  const childIds = new Set(portalChildren.map(child => child.id));
  const sessions = portalSessions.filter(session => { const groupChild = portalChildren.some(child => child.groupId === session.groupId); return groupChild && childIds.size > 0; });
  return <div className="admin-page"><PageHeader icon={CalendarDays} eyebrow={bi('Parent Portal · Schedule', 'بوابة ولي الأمر · الجدول')} title={bi('Family Schedule', 'جدول الأسرة')} description={bi('See the next training moments across the linked children in one family view.', 'شاهد حصص التدريب القادمة للأبناء المرتبطين في عرض أسري واحد.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Linked children', 'الأبناء المرتبطون')} value={portalChildren.length} /><PortalMetric label={bi('Upcoming sessions', 'الحصص القادمة')} value={sessions.length} tone="green" /><PortalMetric label={bi('Sports', 'الرياضات')} value={new Set(portalChildren.map(child => child.sportId)).size} tone="blue" /><PortalMetric label={bi('Preview period', 'الفترة التجريبية')} value="Sep" detail={bi('2026 schedule', 'جدول 2026')} /></section><PortalSection title={bi('Upcoming family sessions', 'حصص الأسرة القادمة')} description={bi('Schedule records are linked to the local player and group fixtures.', 'سجلات الجدول مرتبطة ببيانات اللاعبين والمجموعات المحلية.') }><div className="portal-timeline">{sessions.map(session => { const child = portalChildren.find(item => item.groupId === session.groupId); return <article className="portal-timeline-item" key={session.id}><strong><BilingualText value={getSport(session.sportId)?.name ?? bi('Sport session', 'حصة رياضية')} /></strong><small>{new Date(session.startsAt).toLocaleDateString('en-GB')} · {new Date(session.startsAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</small><div className="portal-session-meta"><span><UserRound size={12} /> {child?.nameEn ?? '—'}</span><PortalStatus label={bi('Scheduled', 'مجدولة')} /></div></article>; })}</div></PortalSection></div>;
}

export function ParentPortalPerformancePage() {
  const average = Math.round(portalChildren.reduce((sum, child) => sum + getPlayerOverall(child.id), 0) / Math.max(portalChildren.length, 1));
  return <div className="admin-page"><PageHeader icon={TrendingUp} eyebrow={bi('Parent Portal · Performance', 'بوابة ولي الأمر · الأداء')} title={bi('Children Performance', 'أداء الأبناء')} description={bi('A family-safe snapshot of each child’s sport-aware development signals.', 'لمحة آمنة للأسرة عن مؤشرات تطور كل طفل حسب الرياضة.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Family average', 'متوسط الأسرة')} value={`${average}/100`} tone="green" /><PortalMetric label={bi('Children reviewed', 'الأبناء المراجعون')} value={portalChildren.length} /><PortalMetric label={bi('Active sports', 'الرياضات النشطة')} value={new Set(portalChildren.map(child => child.sportId)).size} tone="blue" /><PortalMetric label={bi('Latest period', 'الفترة الأحدث')} value="28 Aug" detail={bi('Preview date', 'تاريخ تجريبي')} /></section><PortalSection title={bi('Child development cards', 'بطاقات تطور الأبناء')} description={bi('Scores are derived from sport-specific preview metrics, not a certified ranking.', 'الدرجات مشتقة من مؤشرات رياضية تجريبية وليست ترتيبًا معتمدًا.') }><div className="portal-card-grid">{portalChildren.map(child => { const score = getPlayerOverall(child.id); return <article className="portal-card" key={child.id}><div className="child-card-head"><span className="portal-card-icon"><UserRound size={16} /></span><div><h3>{child.nameEn}</h3><small lang="ar" dir="rtl">{child.nameAr}</small></div><EnterpriseStatus label={bi('Preview', 'تجريبي')} tone="info" /></div><p><BilingualText value={getSport(child.sportId)?.name ?? bi(child.sportId, child.sportId)} /></p><div style={{ marginTop: 13 }}><EnterpriseProgress value={score} label={bi('Overall signal', 'المؤشر الإجمالي')} color="green" /></div></article>; })}</div></PortalSection><PortalTrend label={bi('Family development trend', 'اتجاه تطور الأسرة')} value={`${average}/100`} values={[58, 62, 61, 68, 72, average]} color="green" /></div>;
}

export function ParentPortalFeedbackPage() {
  const feedback = portalChildren.flatMap(child => child.coachFeedback.map(item => ({ ...item, child })));
  return <div className="admin-page"><PageHeader icon={MessageCircle} eyebrow={bi('Parent Portal · Feedback', 'بوابة ولي الأمر · الملاحظات')} title={bi('Coach Feedback', 'ملاحظات المدرب')} description={bi('Keep coaching context visible for supportive family conversations.', 'حافظ على سياق التدريب واضحًا لمحادثات أسرية داعمة.')} actions={<PreviewNotice />} /><PortalSection title={bi('Recent notes', 'الملاحظات الحديثة')} description={bi('These notes are preview records attached to linked children.', 'هذه الملاحظات سجلات تجريبية مرتبطة بالأبناء.')}>{feedback.length ? <div className="portal-timeline">{feedback.map(item => <article className="portal-timeline-item" key={item.id}><div className="feedback-heading"><span className="portal-card-icon"><UserRound size={15} /></span><div><strong>{item.child.nameEn}</strong><small>{item.createdAt}</small></div><PortalStatus label={bi('Preview', 'تجريبي')} tone="neutral" /></div><p><BilingualText value={item.summary} /></p><div className="feedback-pill-row">{item.focusAreas.map(area => <span key={area.en}><BilingualText value={area} /></span>)}</div></article>)}</div> : <div className="enterprise-empty"><MessageCircle size={22} /><h3><BilingualText value={bi('No feedback yet', 'لا توجد ملاحظات بعد')} /></h3><p><BilingualText value={bi('Verified coaching notes will appear here.', 'ستظهر ملاحظات التدريب الموثقة هنا.')} /></p></div>}</PortalSection></div>;
}

export function ParentPortalPaymentsPage() {
  const payments = previewPayments.filter(payment => activeParent.playerIds.includes(payment.playerId));
  const total = payments.reduce((sum, payment) => sum + payment.amount, 0);
  return <div className="admin-page"><PageHeader icon={CreditCard} eyebrow={bi('Parent Portal · Payments', 'بوابة ولي الأمر · المدفوعات')} title={bi('Payments & Invoices', 'المدفوعات والفواتير')} description={bi('A transparent family ledger for preview amounts and states without processing claims.', 'دفتر أسري شفاف للمبالغ والحالات التجريبية دون ادعاء معالجة فعلية.')} actions={<PreviewNotice />} /><section className="portal-metric-grid"><PortalMetric label={bi('Visible total', 'الإجمالي الظاهر')} value={`${total} AED`} tone="green" /><PortalMetric label={bi('Completed', 'مكتمل')} value={payments.filter(payment => payment.status === 'completed').length} /><PortalMetric label={bi('Pending', 'قيد الانتظار')} value={payments.filter(payment => payment.status === 'pending').length} tone="gold" /><PortalMetric label={bi('Linked children', 'الأبناء المرتبطون')} value={new Set(payments.map(payment => payment.playerId)).size} tone="blue" /></section><PortalSection title={bi('Invoice preview', 'معاينة الفواتير')} description={bi('Use these rows to validate future finance workflows; no payment is processed.', 'استخدم هذه الصفوف للتحقق من مسارات المالية المستقبلية؛ لا تتم معالجة أي دفعة.') }><EnterpriseTable caption={bi('Parent payment preview', 'معاينة مدفوعات ولي الأمر')}><thead><tr>{[bi('Reference', 'المرجع'), bi('Child', 'الطفل'), bi('Amount', 'المبلغ'), bi('Method', 'الطريقة'), bi('Date', 'التاريخ'), bi('Status', 'الحالة')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{payments.map(payment => <tr key={payment.id}><td><strong>{payment.id}</strong></td><td>{childFor(payment.playerId)?.nameEn}</td><td><strong>{payment.amount} {payment.currency}</strong></td><td><BilingualText value={payment.method} /></td><td>{payment.date}</td><td><PortalStatus label={bi(payment.status, payment.status === 'completed' ? 'مكتمل' : 'قيد الانتظار')} tone={payment.status === 'completed' ? 'active' : 'pending'} /></td></tr>)}</tbody></EnterpriseTable></PortalSection></div>;
}

export function ParentPortalSubscriptionsPage() {
  return <div className="admin-page"><PageHeader icon={ShieldCheck} eyebrow={bi('Parent Portal · Subscriptions', 'بوابة ولي الأمر · الاشتراكات')} title={bi('Subscriptions', 'الاشتراكات')} description={bi('Review the preview membership plans attached to your children.', 'راجع خطط العضوية التجريبية المرتبطة بأبنائك.')} actions={<PreviewNotice />} /><section className="portal-card-grid">{previewSubscriptions.filter(subscription => activeParent.playerIds.includes(subscription.playerId)).map(subscription => <article className="portal-card" key={subscription.id}><span className="portal-card-icon"><ShieldCheck size={18} /></span><h3><BilingualText value={subscription.plan} /></h3><p>{childFor(subscription.playerId)?.nameEn} · {subscription.amount} {subscription.currency}</p><div className="document-card-footer"><PortalStatus label={bi(subscription.status, subscription.status === 'active' ? 'نشط' : 'قيد الانتظار')} tone={subscription.status === 'active' ? 'active' : 'pending'} /><small><BilingualText value={bi('Renewal', 'التجديد')} /> {subscription.renewal}</small></div></article>)}</section><PortalPreviewCard title={bi('Subscription boundary', 'حدود الاشتراك')} description={bi('This is a local membership preview. It does not renew, charge or change an account.', 'هذه معاينة عضوية محلية. لا تقوم بالتجديد أو الخصم أو تغيير الحساب.')} /></div>;
}

export function ParentPortalDocumentsPage() {
  const [notice, setNotice] = useState(false);
  return <div className="admin-page"><PageHeader icon={FileText} eyebrow={bi('Parent Portal · Documents', 'بوابة ولي الأمر · المستندات')} title={bi('Family Documents', 'مستندات الأسرة')} description={bi('A shared view for membership, consent and certificate references.', 'عرض مشترك لمراجع العضوية والموافقة والشهادات.')} actions={<PreviewNotice />} />{notice && <div className="preview-notice" role="status"><BilingualText value={bi('Document preview opened locally', 'تم فتح معاينة المستند محليًا')} /></div>}<PortalSection title={bi('Document vault', 'خزنة المستندات')}><div className="portal-card-grid">{previewDocuments.map(document => <article className="portal-card" key={document.id}><span className="portal-card-icon"><FileText size={18} /></span><h3><BilingualText value={document.title} /></h3><p><BilingualText value={document.type} /> · {document.updated}</p><UiButton variant="outline" type="button" onClick={() => setNotice(true)}><Download size={13} /><BilingualText value={bi('Open preview', 'فتح المعاينة')} /></UiButton></article>)}</div></PortalSection><PortalPreviewCard title={bi('Private preview storage', 'تخزين المعاينة الخاصة')} description={bi('No uploaded family documents are stored or delivered by this reference implementation.', 'لا يتم تخزين أو تسليم أي مستندات أسرية مرفوعة من خلال هذه النسخة المرجعية.')} /></div>;
}

export function ParentPortalMessagesPage() {
  const [messages, setMessages] = useState([{ id: 'message-preview-001', from: bi('Coach Preview 01', 'مدرب تجريبي 01'), body: bi('Your next training focus is ready for review.', 'تركيزك التدريبي القادم جاهز للمراجعة.'), time: 'Today · 09:20' }]);
  const [draft, setDraft] = useState('');
  const send = () => { if (!draft.trim()) return; setMessages(current => [...current, { id: `message-${current.length + 1}`, from: bi('You · Local preview', 'أنت · معاينة محلية'), body: bi(draft, draft), time: 'Just now · Preview' }]); setDraft(''); };
  return <div className="admin-page"><PageHeader icon={MessageCircle} eyebrow={bi('Parent Portal · Messages', 'بوابة ولي الأمر · الرسائل')} title={bi('Coach Messages', 'رسائل المدرب')} description={bi('A focused family conversation preview with local-only replies.', 'معاينة محادثة أسرية مركزة مع ردود محلية فقط.')} actions={<PreviewNotice />} /><PortalSection title={bi('Conversation preview', 'معاينة المحادثة')} description={bi('Sending appends to this browser session only; it does not claim delivery.', 'الإرسال يضيف إلى جلسة المتصفح فقط ولا يدعي التسليم.') }><div className="message-thread">{messages.map(message => <article className="message-bubble" key={message.id}><div><strong><BilingualText value={message.from} /></strong><small>{message.time}</small></div><p><BilingualText value={message.body} /></p></article>)}</div><div className="portal-composer"><textarea value={draft} onChange={event => setDraft(event.target.value)} placeholder="Write a local preview reply | اكتب ردًا تجريبيًا محليًا" rows={3} /><UiButton type="button" variant="primary" onClick={send}><Send size={14} /><BilingualText value={bi('Append preview reply', 'إضافة رد تجريبي')} /></UiButton></div></PortalSection></div>;
}

export function ParentPortalProfilePage() {
  const [notice, setNotice] = useState(false);
  return <div className="admin-page"><PageHeader icon={HeartHandshake} eyebrow={bi('Parent Portal · Profile', 'بوابة ولي الأمر · الملف الشخصي')} title={bi('Family Profile', 'ملف الأسرة')} description={bi('Review family identity and notification preferences in a preview-safe form.', 'راجع هوية الأسرة وتفضيلات التنبيهات في نموذج آمن للمعاينة.')} actions={<PreviewNotice />} /><section className="portal-profile-hero"><span className="portal-card-icon"><HeartHandshake size={24} /></span><div><h2>{activeParent.nameEn}</h2><p lang="ar" dir="rtl">{activeParent.nameAr}</p><EnterpriseStatus label={bi('Preview profile', 'ملف تجريبي')} tone="info" /></div></section><PortalSection title={bi('Contact preferences', 'تفضيلات الاتصال')} description={bi('Changes are kept in local component state only.', 'تُحفظ التغييرات في حالة المكون المحلية فقط.')}><div className="portal-form-grid"><label><BilingualText value={bi('Email preview', 'معاينة البريد')} /><input defaultValue={activeParent.email} /></label><label><BilingualText value={bi('Phone preview', 'معاينة الهاتف')} /><input defaultValue={activeParent.phone} /></label><label><BilingualText value={bi('Preferred language', 'اللغة المفضلة')} /><select defaultValue={activeParent.preferredLanguage}><option value="en">English | English</option><option value="ar">العربية | Arabic</option></select></label></div><div className="dialog-actions"><UiButton type="button" variant="primary" onClick={() => setNotice(true)}><CheckCircle2 size={14} /><BilingualText value={bi('Apply locally', 'تطبيق محليًا')} /></UiButton></div></PortalSection>{notice && <div className="preview-notice" role="status"><BilingualText value={bi('Profile preference updated locally', 'تم تحديث تفضيل الملف محليًا')} /></div>}<PortalPreviewCard title={bi('Safe pickup preview', 'معاينة الاستلام الآمن')} description={bi('A future pickup pass can be designed here; this reference does not generate a verified credential.', 'يمكن تصميم تصريح استلام مستقبلي هنا؛ لا تنشئ هذه النسخة اعتمادًا موثقًا.') }><div className="portal-qr"><div className="portal-qr-code">{Array.from({ length: 49 }, (_, index) => <i key={index} />)}</div><div className="portal-qr-copy"><strong><BilingualText value={bi('Family pickup pass', 'تصريح استلام الأسرة')} /></strong><p><BilingualText value={bi('Visual-only QR-style presentation for product review.', 'عرض بصري بأسلوب QR للمراجعة فقط.')} /></p></div></div></PortalPreviewCard></div>;
}
