import {
  Activity,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileBarChart,
  FileText,
  Globe2,
  Layers3,
  LayoutDashboard,
  MapPinned,
  Medal,
  Megaphone,
  MessageSquare,
  Settings2,
  ShieldCheck,
  Trophy,
  UsersRound,
  ShoppingBag,
  PackageSearch,
  Boxes,
  Tags,
  type LucideIcon,
} from 'lucide-react';

export type AdminIconKey = 'dashboard' | 'sports' | 'groups' | 'players' | 'parents' | 'coaches' | 'programs' | 'schedules' | 'attendance' | 'performance' | 'countries' | 'branches' | 'subscriptions' | 'payments' | 'reports' | 'content' | 'users' | 'settings' | 'registrations' | 'achievements' | 'events' | 'announcements' | 'messages' | 'audit' | 'store' | 'products' | 'inventory' | 'collections' | 'discounts' | 'orders';

export const adminIconRegistry: Record<AdminIconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  sports: Trophy,
  groups: UsersRound,
  players: Medal,
  parents: UsersRound,
  coaches: ClipboardList,
  programs: Layers3,
  schedules: CalendarDays,
  attendance: ClipboardCheck,
  performance: Activity,
  countries: Globe2,
  branches: MapPinned,
  subscriptions: FileText,
  payments: CreditCard,
  reports: FileBarChart,
  content: FileText,
  users: ShieldCheck,
  settings: Settings2,
  registrations: ClipboardCheck,
  achievements: Medal,
  events: CalendarDays,
  announcements: Megaphone,
  messages: MessageSquare,
  audit: ShieldCheck,
  store: ShoppingBag,
  products: PackageSearch,
  inventory: Boxes,
  collections: Layers3,
  discounts: Tags,
  orders: ClipboardList,
};
