import { Activity, BarChart3, Bell, CalendarDays, CheckCircle2, ClipboardList, CreditCard, FileBarChart, FileText, Globe2, Layers3, MapPinned, MessageSquareText, Palette, Settings2, ShieldCheck, UsersRound } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { PageHeader, PlayerAvatar, StatusBadge } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { demoPrograms } from '../../data/demo/programs';
import { demoPlayers } from '../../data/demo/players';
import { getLatestPlayerMetrics, getPlayerOverall, getSport } from '../../data/demo/selectors';
import { demoTrainingGroups } from '../../data/demo/trainingGroups';
import '../../styles/admin-previews.css';

const modules = {
  groups: { title: bi('Training Groups / Teams', 'الفرق / مجموعات التدريب'), description: bi('Roster, sport and coaching relationships presented from shared preview data.', 'عرض للعلاقات بين القوائم والرياضات والتدريب من البيانات التجريبية المشتركة.') },
  parents: { title: bi('Parents', 'أولياء الأمور'), description: bi('A family-account management concept without invented contact information.', 'تصور لإدارة حسابات الأسر دون اختلاق بيانات تواصل.') },
  coaches: { title: bi('Coaches', 'المدربون'), description: bi('Assignment, workload and evaluation workflow using anonymous coach references.', 'سير عمل للتكليفات والأحمال والتقييم باستخدام مراجع مدربين مجهولة.') },
  programs: { title: bi('Programs', 'البرامج'), description: bi('A visual programme-management workspace connected to the public programme catalogue.', 'مساحة إدارة بصرية للبرامج مرتبطة بكتالوج البرامج العام.') },
  schedules: { title: bi('Schedules', 'الجداول'), description: bi('A calendar structure preview using conceptual blocks rather than operational times.', 'معاينة لهيكل الجدول باستخدام كتل تصورية بدل أوقات تشغيلية.') },
  attendance: { title: bi('Attendance Center', 'مركز الحضور'), description: bi('Attendance status and recent records derived from existing preview players.', 'حالات الحضور والسجلات الأخيرة مشتقة من اللاعبين التجريبيين الحاليين.') },
  performance: { title: bi('Performance Center', 'مركز الأداء'), description: bi('Sport-aware performance cards built from shared metric definitions.', 'بطاقات أداء خاصة بكل رياضة مبنية على تعريفات المؤشرات المشتركة.') },
  countries: { title: bi('Countries', 'الدول'), description: bi('An organization-geography structure without presenting unverified operational countries.', 'هيكل جغرافي للمؤسسة دون عرض دول تشغيلية غير موثقة.') },
  branches: { title: bi('Branches', 'الفروع'), description: bi('Branch templates show hierarchy and sport coverage without fake addresses.', 'قوالب الفروع توضح الهيكل وتغطية الرياضات دون عناوين وهمية.') },
  subscriptions: { title: bi('Subscriptions', 'الاشتراكات'), description: bi('A lifecycle concept for player-linked subscriptions without prices.', 'تصور لدورة حياة الاشتراك المرتبط باللاعب دون أسعار.') },
  payments: { title: bi('Payments', 'المدفوعات'), description: bi('A finance ledger interface preview with no fabricated amounts or transactions.', 'معاينة لواجهة دفتر مالي دون مبالغ أو معاملات مختلقة.') },
  reports: { title: bi('Reports', 'التقارير'), description: bi('A reporting workspace for filters, chart frames and export flow previews.', 'مساحة تقارير للفلاتر وإطارات الرسوم ومعاينة مسار التصدير.') },
  content: { title: bi('Content', 'المحتوى'), description: bi('A bilingual CMS concept for public-site sections and publishing states.', 'تصور لنظام محتوى ثنائي اللغة لأقسام الموقع وحالات النشر.') },
  users: { title: bi('Users & Roles', 'المستخدمون والصلاحيات'), description: bi('Role and permission structure without invented user emails.', 'هيكل للأدوار والصلاحيات دون اختلاق بريد مستخدمين.') },
  settings: { title: bi('Settings', 'الإعدادات'), description: bi('A polished organization-settings concept with no backend persistence.', 'تصور احترافي لإعدادات المؤسسة دون حفظ عبر خادم.') },
} as const;

type Segment = keyof typeof modules;
const previewParents = [
  { id: 'family-preview-a', playerId: 'player-demo-001', label: bi('Family Preview A', 'أسرة تجريبية أ') },
  { id: 'family-preview-b', playerId: 'player-demo-003', label: bi('Family Preview B', 'أسرة تجريبية ب') },
];
const coachRefs = Array.from(new Set(demoTrainingGroups.flatMap(group => group.coachIds)));
const allAttendance = demoPlayers.flatMap(player => player.attendanceRecords.map(record => ({ ...record, player })));
const statusCounts = ['present', 'absent', 'late', 'excused'].map(status => ({ status, count: allAttendance.filter(record => record.status === status).length }));
const paymentStates = [bi('Paid', 'مدفوع'), bi('Pending', 'قيد الانتظار'), bi('Overdue', 'متأخر'), bi('Refunded', 'مسترد')];

function PreviewTitle({ icon: Icon, title, note }: { icon: typeof UsersRound; title: { en: string; ar: string }; note?: { en: string; ar: string } }) { return <div className="amp-section-title"><Icon /><div><h2><BilingualText value={title} /></h2>{note && <p><BilingualText value={note} /></p>}</div></div>; }
function Chip({ value }: { value: { en: string; ar: string } }) { return <span className="amp-chip"><BilingualText value={value} /></span>; }

function GroupsPreview() { return <div className="amp-stack"><PreviewTitle icon={UsersRound} title={bi('Group Overview', 'نظرة على المجموعات')} note={bi('Counts and relationships come from shared preview fixtures.', 'الأعداد والعلاقات تأتي من البيانات التجريبية المشتركة.')} /><div className="amp-card-grid">{demoTrainingGroups.slice(0, 6).map(group => <article className="amp-card" key={group.id}><div className="amp-card-head"><BilingualText value={group.name} /><StatusBadge active={group.status === 'active'} /></div><div className="amp-card-meta"><Chip value={getSport(group.sportId)?.name ?? bi('Sport', 'الرياضة')} /><Chip value={group.level} /></div><div className="amp-big-number">{group.playerIds.length}<small><BilingualText value={bi('Players', 'لاعبون')} /></small></div><p><BilingualText value={bi('Coach Reference', 'مرجع المدرب')} /> <strong>{group.coachIds[0] ?? '—'}</strong></p></article>)}</div></div>; }
function ParentsPreview() { return <div className="amp-stack"><PreviewTitle icon={UsersRound} title={bi('Family Accounts', 'حسابات الأسر')} /><div className="amp-family-grid">{previewParents.map(item => { const player = demoPlayers.find(candidate => candidate.id === item.playerId); return <article key={item.id}><div className="amp-family-head"><div className="amp-family-icon"><UsersRound /></div><BilingualText value={item.label} /><Chip value={bi('Account Preview', 'معاينة الحساب')} /></div>{player && <div className="amp-linked-player"><PlayerAvatar id={player.id} /><div><BilingualText value={bi('Linked Player', 'اللاعب المرتبط')} /><strong>{player.nameEn}</strong><span lang="ar" dir="rtl">{player.nameAr}</span></div></div>}<div className="amp-communication-shell"><MessageSquareText /><BilingualText value={bi('Communication Status', 'حالة التواصل')} /><span>—</span></div></article>; })}</div></div>; }
function CoachesPreview() { return <div className="amp-stack"><PreviewTitle icon={ClipboardList} title={bi('Coach Assignments', 'تكليفات المدربين')} /><div className="amp-card-grid">{coachRefs.slice(0, 8).map(ref => { const groups = demoTrainingGroups.filter(group => group.coachIds.includes(ref)); const sportIds = Array.from(new Set(groups.map(group => group.sportId))); return <article className="amp-card" key={ref}><div className="amp-coach-ref"><span>{ref.slice(-2)}</span><div><BilingualText value={bi('Coach Reference', 'مرجع المدرب')} /><strong>{ref}</strong></div></div><div className="amp-card-meta">{sportIds.map(id => <Chip key={id} value={getSport(id)?.name ?? bi('Sport', 'الرياضة')} />)}</div><p><BilingualText value={bi('Assigned Groups', 'المجموعات المكلف بها')} /> <strong>{groups.length}</strong></p><div className="amp-workload"><i style={{ width: `${Math.min(100, groups.length * 35 + 20)}%` }} /></div></article>; })}</div></div>; }
function ProgramsPreview() { return <div className="amp-stack"><PreviewTitle icon={Layers3} title={bi('Programme Management', 'إدارة البرامج')} /><div className="amp-program-grid">{demoPrograms.map(program => <article key={program.id}><div className={`amp-program-thumb ${program.sportId}`}><Layers3 /></div><div><Chip value={program.sport} /><h3><BilingualText value={program.name} /></h3><p><BilingualText value={program.focus} /></p><div className="amp-card-meta"><Chip value={program.level} /><Chip value={bi('Preview', 'معاينة')} /></div></div></article>)}</div></div>; }
function SchedulesPreview() { const blocks = [bi('Training Block A', 'كتلة تدريب أ'), bi('Training Block B', 'كتلة تدريب ب'), bi('Development Block', 'كتلة تطوير'), bi('Review Block', 'كتلة مراجعة')]; return <div className="amp-stack"><PreviewTitle icon={CalendarDays} title={bi('Schedule Board', 'لوحة الجدول')} note={bi('Conceptual blocks only — no operational times are shown.', 'كتل تصورية فقط — لا يتم عرض أوقات تشغيلية.')} /><div className="amp-calendar"><div className="amp-calendar-head">{[bi('Day A', 'يوم أ'),bi('Day B', 'يوم ب'),bi('Day C', 'يوم ج'),bi('Day D', 'يوم د')].map(day => <BilingualText key={day.en} value={day} />)}</div><div className="amp-calendar-body">{blocks.map((block,index) => <div key={block.en} className={`slot s${index + 1}`}><CalendarDays /><BilingualText value={block} /></div>)}</div></div></div>; }
function AttendancePreview() { return <div className="amp-stack"><PreviewTitle icon={CheckCircle2} title={bi('Attendance Overview', 'نظرة الحضور')} /><div className="amp-stats-row">{statusCounts.map(item => <article key={item.status}><strong>{item.count}</strong><BilingualText value={item.status === 'present' ? bi('Present', 'حاضر') : item.status === 'absent' ? bi('Absent', 'غائب') : item.status === 'late' ? bi('Late', 'متأخر') : bi('Excused', 'بعذر')} /></article>)}</div><div className="amp-table"><div className="amp-table-head"><BilingualText value={bi('Player', 'اللاعب')} /><BilingualText value={bi('Date', 'التاريخ')} /><BilingualText value={bi('Status', 'الحالة')} /></div>{allAttendance.slice(-8).reverse().map(record => <div className="amp-table-row" key={record.id}><span>{record.player.nameEn}<small lang="ar" dir="rtl">{record.player.nameAr}</small></span><span>{record.date}</span><Chip value={record.status === 'present' ? bi('Present', 'حاضر') : record.status === 'absent' ? bi('Absent', 'غائب') : record.status === 'late' ? bi('Late', 'متأخر') : bi('Excused', 'بعذر')} /></div>)}</div></div>; }
function PerformancePreview() { return <div className="amp-stack"><PreviewTitle icon={Activity} title={bi('Sport-Aware Performance', 'الأداء حسب الرياضة')} /><div className="amp-performance-grid">{demoPlayers.slice(0, 6).map(player => { const metrics = getLatestPlayerMetrics(player.id).slice(0, 3); return <article key={player.id}><div className="amp-player-line"><PlayerAvatar id={player.id} /><div><strong>{player.nameEn}</strong><span lang="ar" dir="rtl">{player.nameAr}</span><BilingualText value={getSport(player.sportId)?.name ?? bi('Sport', 'الرياضة')} /></div><b>{getPlayerOverall(player.id)}</b></div>{metrics.map(metric => <div className="amp-metric-line" key={metric.definition.id}><BilingualText value={metric.definition.name} /><span><i style={{ width: `${metric.current?.value ?? 0}%` }} /></span><strong>{metric.current?.value ?? '—'}</strong></div>)}</article>; })}</div></div>; }
function CountriesPreview() { return <div className="amp-stack"><PreviewTitle icon={Globe2} title={bi('Organization Geography', 'جغرافيا المؤسسة')} note={bi('No country is presented as an operational fact.', 'لا يتم عرض أي دولة كحقيقة تشغيلية.')} /><div className="amp-geo"><div className="amp-globe"><Globe2 /><i /><i /><i /></div><div className="amp-geo-slots">{[bi('Country Slot A', 'خانة دولة أ'),bi('Country Slot B', 'خانة دولة ب'),bi('Country Slot C', 'خانة دولة ج')].map((slot,index) => <article key={slot.en}><span>{String(index + 1).padStart(2,'0')}</span><BilingualText value={slot} /><Chip value={bi('Structure Preview', 'معاينة الهيكل')} /></article>)}</div></div></div>; }
function BranchesPreview() { return <div className="amp-stack"><PreviewTitle icon={MapPinned} title={bi('Branch Structure', 'هيكل الفروع')} note={bi('No addresses or areas are invented.', 'لا يتم اختلاق عناوين أو مناطق.')} /><div className="amp-branch-grid">{[0,1,2].map(index => <article key={index}><MapPinned /><h3><BilingualText value={bi(`Branch Preview 0${index + 1}`, `فرع تجريبي 0${index + 1}`)} /></h3><div className="amp-card-meta"><Chip value={bi('Sport Coverage', 'تغطية الرياضات')} /><Chip value={bi('Status Preview', 'معاينة الحالة')} /></div><div className="amp-branch-bars"><span /><span /><span /></div><p><BilingualText value={bi('Players · Coaches · Programs', 'اللاعبون · المدربون · البرامج')} /></p></article>)}</div></div>; }
function SubscriptionsPreview() { return <div className="amp-stack"><PreviewTitle icon={CreditCard} title={bi('Subscription Lifecycle', 'دورة حياة الاشتراك')} /><div className="amp-subscription-grid">{demoPlayers.slice(0,4).map((player,index) => <article key={player.id}><div className="amp-player-line"><PlayerAvatar id={player.id} /><div><strong>{player.nameEn}</strong><span lang="ar" dir="rtl">{player.nameAr}</span></div></div><div className="amp-life"><span className="done"><BilingualText value={bi('Start', 'البداية')} /></span><i /><span className={index % 2 ? '' : 'done'}><BilingualText value={bi('Active', 'نشط')} /></span><i /><span><BilingualText value={bi('Renewal', 'التجديد')} /></span></div><strong className="amp-no-price">—</strong><small><BilingualText value={bi('No price in preview', 'لا يوجد سعر في المعاينة')} /></small></article>)}</div></div>; }
function PaymentsPreview() { return <div className="amp-stack"><PreviewTitle icon={CreditCard} title={bi('Payments Ledger', 'دفتر المدفوعات')} note={bi('Status examples only; no real financial transactions.', 'أمثلة حالات فقط دون معاملات مالية حقيقية.')} /><div className="amp-ledger"><div className="amp-table-head"><BilingualText value={bi('Reference', 'المرجع')} /><BilingualText value={bi('Status', 'الحالة')} /><BilingualText value={bi('Amount', 'المبلغ')} /></div>{paymentStates.map((status,index) => <div className="amp-table-row" key={status.en}><span>PREVIEW-{String(index + 1).padStart(3,'0')}</span><Chip value={status} /><strong>—</strong></div>)}</div></div>; }
function ReportsPreview() { return <div className="amp-stack"><PreviewTitle icon={FileBarChart} title={bi('Reports Workspace', 'مساحة التقارير')} /><div className="amp-report-layout"><div className="amp-report-categories">{[bi('Attendance Report', 'تقرير الحضور'),bi('Player Progress', 'تقدم اللاعبين'),bi('Programme Activity', 'نشاط البرامج')].map(item => <article key={item.en}><FileText /><BilingualText value={item} /><Chip value={bi('Export Preview', 'معاينة التصدير')} /></article>)}</div><div className="amp-chart-frame"><div className="amp-chart-head"><BarChart3 /><BilingualText value={bi('Chart Preview', 'معاينة الرسم')} /></div><div className="amp-bars">{[42,68,54,82,64,76,58].map((height,index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div></div></div>; }
function ContentPreview() { return <div className="amp-stack"><PreviewTitle icon={FileText} title={bi('Content Workspace', 'مساحة المحتوى')} /><div className="amp-content-grid">{[bi('Homepage Sections', 'أقسام الصفحة الرئيسية'),bi('Sports Content', 'محتوى الرياضات'),bi('Programs Content', 'محتوى البرامج'),bi('News & Events', 'الأخبار والفعاليات')].map((item,index) => <article key={item.en}><div className="amp-content-thumb"><FileText /></div><h3><BilingualText value={item} /></h3><Chip value={index % 2 ? bi('Draft Preview', 'معاينة مسودة') : bi('Publish Status', 'حالة النشر')} /><div className="amp-content-lines"><span /><span /><span /></div></article>)}</div></div>; }
function UsersPreview() { const roles = [bi('Super Admin', 'الإدارة الرئيسية'),bi('Coach', 'المدرب'),bi('Parent', 'ولي الأمر'),bi('Player', 'اللاعب')]; return <div className="amp-stack"><PreviewTitle icon={ShieldCheck} title={bi('Roles & Permissions', 'الأدوار والصلاحيات')} note={bi('No fake user emails are displayed.', 'لا يتم عرض بريد مستخدمين وهمي.')} /><div className="amp-role-grid">{roles.map((role,index) => <article key={role.en}><ShieldCheck /><h3><BilingualText value={role} /></h3><div className="amp-permission-row"><BilingualText value={bi('View', 'عرض')} /><span className="on" /></div><div className="amp-permission-row"><BilingualText value={bi('Manage', 'إدارة')} /><span className={index < 2 ? 'on' : ''} /></div><div className="amp-permission-row"><BilingualText value={bi('Reports', 'تقارير')} /><span className={index === 0 ? 'on' : ''} /></div></article>)}</div></div>; }
function SettingsPreview() { const items = [{ icon: Palette, title: bi('Brand', 'الهوية') },{ icon: Bell, title: bi('Notifications', 'الإشعارات') },{ icon: Globe2, title: bi('Language', 'اللغة') },{ icon: Layers3, title: bi('Organization', 'المؤسسة') },{ icon: ShieldCheck, title: bi('Privacy', 'الخصوصية') }]; return <div className="amp-stack"><PreviewTitle icon={Settings2} title={bi('Organization Settings', 'إعدادات المؤسسة')} /><div className="amp-settings-grid">{items.map(({icon:Icon,title},index) => <article key={title.en}><Icon /><div><h3><BilingualText value={title} /></h3><p><BilingualText value={bi('Interface preview', 'معاينة الواجهة')} /></p></div><span className={`amp-toggle ${index < 2 ? 'on' : ''}`} /></article>)}</div><div className="amp-settings-note"><BilingualText value={bi('Changes are not persisted in this visual prototype.', 'لا يتم حفظ التغييرات في هذا النموذج البصري.')} /></div></div>; }

const renderers: Record<Segment, () => JSX.Element> = { groups: GroupsPreview, parents: ParentsPreview, coaches: CoachesPreview, programs: ProgramsPreview, schedules: SchedulesPreview, attendance: AttendancePreview, performance: PerformancePreview, countries: CountriesPreview, branches: BranchesPreview, subscriptions: SubscriptionsPreview, payments: PaymentsPreview, reports: ReportsPreview, content: ContentPreview, users: UsersPreview, settings: SettingsPreview };

export function AdminFutureModulePage() {
  const raw = useLocation().pathname.split('/').filter(Boolean)[1] as Segment | undefined; const segment: Segment = raw && raw in modules ? raw : 'settings'; const definition = modules[segment]; const Preview = renderers[segment];
  return <div className="admin-page amp-page"><PageHeader eyebrow={bi('UI Preview', 'معاينة الواجهة')} title={definition.title} description={definition.description} /><div className="amp-preview-banner"><span /><BilingualText value={bi('High-fidelity owner demo — no backend actions are claimed.', 'عرض تجريبي عالي الجودة للمالك — دون ادعاء عمليات خادم فعلية.')} /></div><Preview /></div>;
}
