import { ArrowRight, Filter, Plus, Search, SlidersHorizontal, X, Trash2, Power } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, StatusBadge, UserAvatar } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { useUsers, useCreateUser, useUpdateUser, useDeleteUser } from '../../admin/data/adminHooks';
import { UiButton } from '../../components/ui/UiPrimitives';

export function AdminUsersPage() {
  const [query,setQuery]=useState(''); const [role,setRole]=useState('all'); const [status,setStatus]=useState('all'); const [showForm,setShowForm]=useState(false); const [filtersOpen,setFiltersOpen]=useState(false); const [feedback,setFeedback]=useState('');
  const { data, loading, refetch }=useUsers({page:1,pageSize:100});
  const { create, loading:createLoading }=useCreateUser(); const { update, loading:updateLoading }=useUpdateUser(); const { delete:deleteFn, loading:deleteLoading }=useDeleteUser();
  const users=useMemo(()=>data?.items.filter(user=>`${user.name.en} ${user.name.ar} ${user.email}`.toLowerCase().includes(query.toLowerCase())&&(role==='all'||user.roles.some(r=>r.toLowerCase()===role))&&(status==='all'||user.status===status))??[],[data,query,role,status]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const nameEn=String(fd.get('nameEn')||'').trim(); const nameAr=String(fd.get('nameAr')||'').trim(); const email=String(fd.get('email')||'').trim(); const selectedRole=String(fd.get('role')||'viewer'); const nextStatus=String(fd.get('status')||'active') as 'active'|'inactive'; if(!nameEn||!nameAr||!email){setFeedback('Name and email are required | الاسم والبريد مطلوبان');return;} await create({name:{en:nameEn,ar:nameAr},email,roles:[selectedRole],status:nextStatus}); await refetch(); setShowForm(false); setFeedback('User created in preview store | تم إنشاء المستخدم في مخزن المعاينة');};
  const toggle=async(id:string,current:'active'|'inactive')=>{await update(id,{status:current==='active'?'inactive':'active'}); await refetch();};
  const remove=async(id:string)=>{if(!window.confirm('Delete this preview user? | حذف مستخدم المعاينة؟'))return; await deleteFn(id); await refetch();};
  return <div className="admin-page"><PageHeader eyebrow={bi('Access Management','إدارة الوصول')} title={bi('Users & Roles','المستخدمون والصلاحيات')} description={bi('Operational preview access directory. Creates, status changes and deletions persist in this browser.','دليل وصول تشغيلي للمعاينة. الإنشاء وتغيير الحالة والحذف تستمر في هذا المتصفح.')} actions={<button className="admin-primary-button" onClick={()=>setShowForm(true)}><Plus/><BilingualText value={bi('Add User','إضافة مستخدم')}/></button>}/>{feedback&&<p className="preview-warning" role="status">{feedback}</p>}
    <section className="player-filter-bar"><label className="filter-search"><Search/><span className="sr-only">Search Users | البحث عن المستخدمين</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Users | البحث عن المستخدمين"/></label><button className="filter-drawer-button" onClick={()=>setFiltersOpen(!filtersOpen)}><Filter/><BilingualText value={bi('Filters','الفلاتر')}/></button><div className={`filter-fields ${filtersOpen?'open':''}`}><label><BilingualText value={bi('Role','الدور')}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All Roles | كل الأدوار</option><option value="admin">Admin | مدير</option><option value="manager">Manager | مشرف</option><option value="coach">Coach | مدرب</option><option value="viewer">Viewer | مشاهد</option></select></label><label><BilingualText value={bi('Status','الحالة')}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Statuses | كل الحالات</option><option value="active">Active | نشط</option><option value="inactive">Inactive | غير نشط</option></select></label><span className="result-count"><SlidersHorizontal/><BilingualText value={bi(`${users.length} records`,`${users.length} سجل`)}/></span></div></section>
    {loading?<p><BilingualText value={bi('Loading users…','جارٍ تحميل المستخدمين…')}/></p>:<><section className="player-table-wrap"><table className="player-table"><caption className="sr-only">Users Directory | دليل المستخدمين</caption><thead><tr>{[bi('Avatar','الصورة'),bi('Name','الاسم'),bi('Email','البريد'),bi('Roles','الأدوار'),bi('Status','الحالة'),bi('Last Login','آخر دخول'),bi('Actions','الإجراءات')].map(l=><th key={l.en}><BilingualText value={l}/></th>)}</tr></thead><tbody>{users.map(user=><tr key={user.id}><td><UserAvatar name={user.name.en}/></td><td><BilingualText value={user.name}/></td><td><code>{user.email}</code></td><td>{user.roles.join(', ')}</td><td><StatusBadge active={user.status==='active'}/></td><td>{user.lastLogin?new Date(user.lastLogin).toLocaleDateString():'—'}</td><td><div className="page-actions"><Link className="row-action" to={`/admin/users/${user.id}`} aria-label={`Open ${user.name.en}`}><ArrowRight/></Link><button className="row-action" disabled={updateLoading} onClick={()=>void toggle(user.id,user.status)} aria-label="Toggle access"><Power/></button><button className="row-action" disabled={deleteLoading} onClick={()=>void remove(user.id)} aria-label="Delete preview user"><Trash2/></button></div></td></tr>)}</tbody></table></section><section className="player-mobile-list">{users.map(user=><article className="player-mobile-card" key={user.id}><div className="mobile-player-head"><UserAvatar name={user.name.en}/><BilingualText value={user.name}/><StatusBadge active={user.status==='active'}/></div><div className="mobile-player-meta"><span><BilingualText value={bi('Email','البريد')}/><code>{user.email}</code></span><span><BilingualText value={bi('Roles','الأدوار')}/>{user.roles.join(', ')}</span></div><Link className="admin-link-button" to={`/admin/users/${user.id}`}><BilingualText value={bi('Open User Record','فتح سجل المستخدم')}/><ArrowRight/></Link></article>)}</section></>}
    {showForm&&<div className="admin-modal-backdrop" role="presentation" onMouseDown={()=>setShowForm(false)}><section className="admin-modal" role="dialog" aria-modal="true" aria-label="Add User" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><BilingualText value={bi('Add User','إضافة مستخدم')}/><small><BilingualText value={bi('Browser-persistent preview record','سجل معاينة محفوظ في المتصفح')}/></small></div><button className="admin-icon-button" onClick={()=>setShowForm(false)} aria-label="Close | إغلاق"><X/></button></div><form onSubmit={e=>void submit(e)}><div className="preview-form-grid"><label>English name<input name="nameEn" required/></label><label>الاسم العربي<input name="nameAr" required dir="rtl"/></label><label>Email<input name="email" type="email" required/></label><label><BilingualText value={bi('Role','الدور')}/><select name="role"><option value="admin">Admin</option><option value="manager">Manager</option><option value="coach">Coach</option><option value="viewer">Viewer</option></select></label><label><BilingualText value={bi('Status','الحالة')}/><select name="status"><option value="active">Active | نشط</option><option value="inactive">Inactive | غير نشط</option></select></label></div><div className="ui-dialog-actions"><UiButton type="button" variant="ghost" onClick={()=>setShowForm(false)}><BilingualText value={bi('Cancel','إلغاء')}/></UiButton><UiButton type="submit" disabled={createLoading}><BilingualText value={bi(createLoading?'Saving…':'Create User',createLoading?'جارٍ الحفظ…':'إنشاء المستخدم')}/></UiButton></div></form></section></div>}
  </div>;
}
