import { ArrowRight, Filter, Plus, Search, SlidersHorizontal, X, ClipboardCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, StatusBadge } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { useRegistrations, useCreateRegistration, useUpdateRegistration, useDeleteRegistration } from '../../admin/data/adminHooks';
import { demoPlayers } from '../../data/demo/players';
import { demoPrograms } from '../../data/demo/programs';

export function AdminRegistrationsPage() {
  const [query, setQuery] = useState(''); const [program, setProgram] = useState('all'); const [status, setStatus] = useState('all'); const [showForm, setShowForm] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false);
  const { data, loading, params, setParams, refetch } = useRegistrations({ page: 1, pageSize: 20 });
  const { create, loading: createLoading } = useCreateRegistration();
  const { update, loading: updateLoading } = useUpdateRegistration();
  const { delete: deleteFn, loading: deleteLoading } = useDeleteRegistration();

  const registrations = useMemo(() => data?.items.filter(reg => {
    const player = demoPlayers.find(p => p.id === reg.playerId);
    const matchesQuery = player ? `${player.nameEn} ${player.nameAr} ${reg.id}`.toLowerCase().includes(query.toLowerCase()) : reg.id.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (program === 'all' || reg.programId === program) && (status === 'all' || reg.status === status);
  }) ?? [], [data, query, program, status]);

  return <div className="admin-page">
    <PageHeader eyebrow={bi('Training Operations', 'عمليات التدريب')} title={bi('Registrations', 'التسجيلات')} description={bi('Preview of program registrations and enrollment status.', 'معاينة لتسجيلات البرامج وحالة التسجيل.')} actions={<button className="admin-primary-button" onClick={() => setShowForm(true)}><Plus /><BilingualText value={bi('Add Registration', 'إضافة تسجيل')} /></button>} />
    <section className="player-filter-bar">
      <label className="filter-search"><Search /><span className="sr-only">Search Registrations | البحث عن التسجيلات</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Registrations | البحث عن التسجيلات" /></label>
      <button className="filter-drawer-button" onClick={() => setFiltersOpen(!filtersOpen)}><Filter /><BilingualText value={bi('Filters', 'الفلاتر')} /></button>
      <div className={`filter-fields ${filtersOpen ? 'open' : ''}`}>
        <label><BilingualText value={bi('Program', 'البرنامج')} /><select value={program} onChange={event => setProgram(event.target.value)}><option value="all">All Programs | كل البرامج</option>{demoPrograms.map(item => <option key={item.id} value={item.id}>{item.name.en} | {item.name.ar}</option>)}</select></label>
        <label><BilingualText value={bi('Status', 'الحالة')} /><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All Statuses | كل الحالات</option><option value="pending">Pending | قيد الانتظار</option><option value="confirmed">Confirmed | مؤكد</option><option value="cancelled">Cancelled | ملغي</option><option value="waitlisted">Waitlisted | في قائمة الانتظار</option></select></label>
        <span className="result-count"><SlidersHorizontal /><BilingualText value={bi(`${registrations.length} preview records`, `${registrations.length} سجلات تجريبية`)} /></span>
      </div>
    </section>
    <section className="player-table-wrap"><table className="player-table"><caption className="sr-only">Registrations Directory | دليل التسجيلات</caption><thead><tr>{[bi('Registration ID', 'رقم التسجيل'), bi('Player', 'اللاعب'), bi('Program', 'البرنامج'), bi('Group', 'المجموعة'), bi('Status', 'الحالة'), bi('Requested', 'تاريخ الطلب'), bi('Confirmed', 'تاريخ التأكيد'), bi('Actions', 'الإجراءات')].map(label => <th key={label.en} scope="col"><BilingualText value={label} /></th>)}</tr></thead><tbody>{registrations.map(reg => { const player = demoPlayers.find(p => p.id === reg.playerId); const program = demoPrograms.find(p => p.id === reg.programId); return <tr key={reg.id}><td><code>{reg.id}</code></td><td>{player && <BilingualText value={{ en: player.nameEn, ar: player.nameAr }} />}</td><td>{program && <BilingualText value={program.name} />}</td><td>{reg.groupId || <BilingualText value={bi('Not assigned', 'غير معين')} />}</td><td><StatusBadge active={reg.status === 'confirmed'} /></td><td>{new Date(reg.requestedAt).toLocaleDateString()}</td><td>{reg.confirmedAt ? new Date(reg.confirmedAt).toLocaleDateString() : <BilingualText value={bi('—', '—')} />}</td><td><Link className="row-action" to={`/admin/registrations/${reg.id}`} aria-label={`Open ${reg.id} | فتح ${reg.id}`}><ArrowRight /></Link></td></tr>; })}</tbody></table></section>
    <section className="player-mobile-list">{registrations.map(reg => { const player = demoPlayers.find(p => p.id === reg.playerId); const program = demoPrograms.find(p => p.id === reg.programId); return <article className="player-mobile-card" key={reg.id}><div className="mobile-player-head"><ClipboardCheck size={24} /><div><BilingualText value={{ en: reg.id, ar: reg.id }} /><StatusBadge active={reg.status === 'confirmed'} /></div></div><div className="mobile-player-meta"><span><BilingualText value={bi('Player', 'اللاعب')} />{player && <BilingualText value={{ en: player.nameEn, ar: player.nameAr }} />}</span><span><BilingualText value={bi('Program', 'البرنامج')} />{program && <BilingualText value={program.name} />}</span><span><BilingualText value={bi('Status', 'الحالة')} /><BilingualText value={{ en: reg.status, ar: reg.status }} /></span></div><Link className="admin-link-button" to={`/admin/registrations/${reg.id}`}><BilingualText value={bi('Open Registration', 'فتح التسجيل')} /><ArrowRight /></Link></article>; })}</section>
    {showForm && <div className="admin-modal-backdrop" role="presentation" onMouseDown={() => setShowForm(false)}><section className="admin-modal" role="dialog" aria-modal="true" aria-label="Add Registration Preview Form | نموذج معاينة إضافة تسجيل" onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><BilingualText value={bi('Add Registration', 'إضافة تسجيل')} /><small><BilingualText value={bi('Local Preview State Only', 'حالة معاينة محلية فقط')} /></small></div><button className="admin-icon-button" onClick={() => setShowForm(false)} aria-label="Close | إغلاق"><X /></button></div><div className="preview-warning"><BilingualText value={bi('This form does not save to a database. It prepares the future data-entry experience only.', 'هذا النموذج لا يحفظ في قاعدة بيانات. إنه يجهز تجربة إدخال البيانات المستقبلية فقط.')} /></div><div className="preview-form-grid"><label><BilingualText value={bi('Player', 'اللاعب')} /><select><option>Select Player | اختر اللاعب</option>{demoPlayers.map(p => <option key={p.id} value={p.id}>{p.nameEn} | {p.nameAr}</option>)}</select></label><label><BilingualText value={bi('Program', 'البرنامج')} /><select><option>Select Program | اختر البرنامج</option>{demoPrograms.map(p => <option key={p.id} value={p.id}>{p.name.en} | {p.name.ar}</option>)}</select></label><label><BilingualText value={bi('Status', 'الحالة')} /><select><option value="pending">Pending | قيد الانتظار</option><option value="confirmed">Confirmed | مؤكد</option></select></label></div><button className="admin-secondary-button" onClick={() => setShowForm(false)}><BilingualText value={bi('Close Preview Form', 'إغلاق نموذج المعاينة')} /></button></section></div>}
  </div>;
}