import { ArrowRight, Filter, Plus, SlidersHorizontal, UserRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { usePlayers } from '../../admin/data/adminHooks';
import { PageHeader, PlayerAvatar } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { EnterpriseEmpty, EnterpriseSelect, EnterpriseStatus, EnterpriseTable, EnterpriseToolbar, ExportMenu, PreviewNotice, RowMenu } from '../../components/enterprise/EnterpriseUI';
import { UiButton, UiDialog, UiPreviewState } from '../../components/ui/UiPrimitives';
import { demoSports } from '../../data/demo/sports';
import { getGroup, getSport } from '../../data/demo/selectors';

export function AdminPlayersPage() {
  const [query, setQuery] = useState('');
  const [sport, setSport] = useState('all');
  const [status, setStatus] = useState('all');
  const [selected, setSelected] = useState<string[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [notice, setNotice] = useState(false);
  const { data, loading, error } = usePlayers({ page: 1, pageSize: 50 });
  const players = useMemo(() => (data?.items ?? []).filter(player => {
    const haystack = `${player.nameEn} ${player.nameAr} ${player.id}`.toLowerCase();
    const active = typeof player.status === 'object' ? player.status.en.toLowerCase() : 'active';
    return haystack.includes(query.toLowerCase()) && (sport === 'all' || player.sportId === sport) && (status === 'all' || active === status);
  }), [data, query, sport, status]);
  const allSelected = players.length > 0 && players.every(player => selected.includes(player.id));
  const toggleAll = () => setSelected(allSelected ? [] : players.map(player => player.id));
  const toggleSelected = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const reset = () => { setQuery(''); setSport('all'); setStatus('all'); setSelected([]); };
  return <div className="admin-page">
    <PageHeader icon={UserRound} eyebrow={bi('Player Management', 'إدارة اللاعبين')} title={bi('Player Directory', 'دليل اللاعبين')} description={bi('A high-density roster view linked to sports, groups, attendance and performance preview data.', 'عرض قائمة عالي الكثافة مرتبط بالرياضات والمجموعات والحضور وبيانات الأداء التجريبية.')} actions={<div className="page-action-stack"><UiButton variant="primary" type="button" onClick={() => setShowForm(true)}><Plus size={15} /><BilingualText value={bi('Add player', 'إضافة لاعب')} /></UiButton><PreviewNotice /></div>} />
    {notice && <div className="preview-notice" role="status"><BilingualText value={bi('Preview record prepared locally', 'تم تجهيز السجل التجريبي محليًا')} /></div>}
    <EnterpriseToolbar query={query} onQueryChange={setQuery} queryLabel={bi('Search players or IDs', 'البحث عن اللاعبين أو المعرفات')} filters={<><EnterpriseSelect label={bi('Sport', 'الرياضة')} value={sport} onChange={setSport} options={[{ value: 'all', label: bi('All sports', 'كل الرياضات') }, ...demoSports.map(item => ({ value: item.id, label: item.name }))]} /><EnterpriseSelect label={bi('Status', 'الحالة')} value={status} onChange={setStatus} options={[{ value: 'all', label: bi('All statuses', 'كل الحالات') }, { value: 'active', label: bi('Active', 'نشط') }, { value: 'inactive', label: bi('Inactive', 'غير نشط') }]} /></>} resultCount={bi(`${players.length} visible · ${selected.length} selected`, `${players.length} ظاهر · ${selected.length} محدد`)} actions={<><ExportMenu filename="players-preview.csv" headers={['Player', 'Sport', 'Group', 'Age', 'Attendance', 'Performance']} rows={players.map(player => [player.nameEn, getSport(player.sportId)?.name.en ?? player.sportId, getGroup(player.groupId)?.name.en ?? '-', player.age ?? '-', `${player.attendanceRate}%`, player.performanceScore])} /><UiButton variant="outline" type="button" onClick={reset}><SlidersHorizontal size={14} /><BilingualText value={bi('Reset', 'إعادة ضبط')} /></UiButton></>} />
    {loading && <div className="enterprise-panel"><UiPreviewState title={bi('Loading roster preview', 'جارٍ تحميل معاينة القائمة')} description={bi('Preparing the isolated player records.', 'جارٍ تجهيز سجلات اللاعبين المعزولة.')} /></div>}
    {error && <div className="enterprise-panel"><UiPreviewState title={bi('Roster preview unavailable', 'تعذر عرض معاينة القائمة')} description={bi('The preview gateway returned an error.', 'أعاد مصدر المعاينة خطأً.')} /></div>}
    {!loading && !error && <>
      {selected.length > 0 && <div className="bulk-preview-bar"><span><BilingualText value={bi(`${selected.length} players selected`, `تم تحديد ${selected.length} لاعبين`)} /></span><UiButton type="button" variant="outline" onClick={() => { setNotice(true); setSelected([]); }}><BilingualText value={bi('Mark reviewed locally', 'تحديد كمراجع محليًا')} /></UiButton><UiButton type="button" variant="ghost" onClick={() => setSelected([])}><BilingualText value={bi('Clear selection', 'مسح التحديد')} /></UiButton></div>}
      {players.length ? <EnterpriseTable caption={bi('Player enterprise roster', 'قائمة اللاعبين المؤسسية')}><thead><tr><th><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Select all players | تحديد كل اللاعبين" /></th>{[bi('Player', 'اللاعب'), bi('Sport', 'الرياضة'), bi('Group', 'المجموعة'), bi('Age', 'العمر'), bi('Level', 'المستوى'), bi('Attendance', 'الحضور'), bi('Performance', 'الأداء'), bi('Status', 'الحالة'), bi('Actions', 'الإجراءات')].map(label => <th key={label.en}><BilingualText value={label} /></th>)}</tr></thead><tbody>{players.map(player => { const active = typeof player.status === 'object' ? player.status.en.toLowerCase() === 'active' : true; return <tr key={player.id}><td><input type="checkbox" checked={selected.includes(player.id)} onChange={() => toggleSelected(player.id)} aria-label={`Select ${player.nameEn} | تحديد ${player.nameAr}`} /></td><td><div className="table-entity"><PlayerAvatar id={player.id} /><span><strong><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></strong><small>{player.id}</small></span></div></td><td><BilingualText value={getSport(player.sportId)?.name ?? bi(player.sportId, player.sportId)} /></td><td><BilingualText value={getGroup(player.groupId)?.name ?? bi('Not assigned', 'غير معين')} /></td><td>{player.age ?? '—'}</td><td><BilingualText value={player.level} /></td><td><strong>{player.attendanceRate}%</strong><small><BilingualText value={bi('derived', 'مشتق')} /></small></td><td><strong>{player.performanceScore}/100</strong></td><td><EnterpriseStatus label={active ? bi('Active', 'نشط') : bi('Inactive', 'غير نشط')} tone={active ? 'active' : 'neutral'} /></td><td><RowMenu actions={[{ label: bi('Open player record', 'فتح سجل اللاعب'), onClick: () => { window.location.href = `/admin/players/${player.id}`; } }, { label: bi('Mark reviewed locally', 'تحديد كمراجع محليًا'), onClick: () => setNotice(true) }]} /></td></tr>; })}</tbody></EnterpriseTable> : <EnterpriseEmpty title={bi('No players match these filters', 'لا يوجد لاعبون يطابقون هذه الفلاتر')} description={bi('Reset the filters to return to the preview roster.', 'أعد ضبط الفلاتر للعودة إلى قائمة المعاينة.')} action={<UiButton type="button" variant="outline" onClick={reset}><Filter size={14} /><BilingualText value={bi('Reset filters', 'إعادة ضبط الفلاتر')} /></UiButton>} />}
      <section className="player-mobile-list">{players.map(player => <article className="player-mobile-card" key={player.id}><div className="mobile-player-head"><PlayerAvatar id={player.id} /><div><strong><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></strong><small>{player.id}</small></div><EnterpriseStatus label={bi('Active', 'نشط')} tone="active" /></div><div className="mobile-player-meta"><span><BilingualText value={bi('Sport', 'الرياضة')} /><BilingualText value={getSport(player.sportId)?.name ?? bi(player.sportId, player.sportId)} /></span><span><BilingualText value={bi('Attendance', 'الحضور')} /><strong>{player.attendanceRate}%</strong></span><span><BilingualText value={bi('Performance', 'الأداء')} /><strong>{player.performanceScore}/100</strong></span></div><Link className="admin-link-button" to={`/admin/players/${player.id}`}><BilingualText value={bi('Open player record', 'فتح سجل اللاعب')} /><ArrowRight /></Link></article>)}</section>
    </>}
    <UiDialog open={showForm} onClose={() => setShowForm(false)} title={bi('Add player preview', 'معاينة إضافة لاعب')} description={bi('This local form demonstrates the future intake flow without claiming persistence.', 'يوضح هذا النموذج المحلي مسار الإدخال المستقبلي دون ادعاء الحفظ الدائم.')}><div className="preview-form-grid"><label><BilingualText value={bi('Player name', 'اسم اللاعب')} /><input placeholder="Preview name | اسم تجريبي" /></label><label><BilingualText value={bi('Sport', 'الرياضة')} /><select><option>Football | كرة القدم</option>{demoSports.slice(1).map(item => <option key={item.id}>{item.name.en} | {item.name.ar}</option>)}</select></label><div className="dialog-actions"><UiButton type="button" variant="primary" onClick={() => { setShowForm(false); setNotice(true); }}><BilingualText value={bi('Prepare local preview', 'تجهيز المعاينة المحلية')} /></UiButton><UiButton type="button" variant="ghost" onClick={() => setShowForm(false)}><BilingualText value={bi('Cancel', 'إلغاء')} /></UiButton></div></div></UiDialog>
  </div>;
}
