import { ArrowRight, Filter, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, PlayerAvatar, StatusBadge } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { demoPlayers } from '../../data/demo/players';
import { getGroup, getPlayerOverall, getSport } from '../../data/demo/selectors';
import { demoSports } from '../../data/demo/sports';

export function AdminPlayersPage() {
  const [query, setQuery] = useState(''); const [sport, setSport] = useState('all'); const [status, setStatus] = useState('all'); const [showForm, setShowForm] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false);
  const players = useMemo(() => demoPlayers.filter(player => {
    const matchesQuery = `${player.nameEn} ${player.nameAr} ${player.id}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (sport === 'all' || player.sportId === sport) && (status === 'all' || player.status.en.toLowerCase() === status);
  }), [query, sport, status]);
  return <div className="admin-page">
    <PageHeader eyebrow={bi('Player Management', 'إدارة اللاعبين')} title={bi('Player Directory', 'دليل اللاعبين')} description={bi('An anonymized preview directory connected to sports, training groups, attendance and sport-aware performance.', 'دليل تجريبي مجهول الهوية مرتبط بالرياضات ومجموعات التدريب والحضور والأداء حسب الرياضة.')} actions={<button className="admin-primary-button" onClick={() => setShowForm(true)}><Plus /><BilingualText value={bi('Add Player', 'إضافة لاعب')} /></button>} />
    <section className="player-filter-bar">
      <label className="filter-search"><Search /><span className="sr-only">Search Players | البحث عن اللاعبين</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Players | البحث عن اللاعبين" /></label>
      <button className="filter-drawer-button" onClick={() => setFiltersOpen(!filtersOpen)}><Filter /><BilingualText value={bi('Filters', 'الفلاتر')} /></button>
      <div className={`filter-fields ${filtersOpen ? 'open' : ''}`}>
        <label><BilingualText value={bi('Sport', 'الرياضة')} /><select value={sport} onChange={event => setSport(event.target.value)}><option value="all">All Sports | كل الرياضات</option>{demoSports.map(item => <option key={item.id} value={item.id}>{item.name.en} | {item.name.ar}</option>)}</select></label>
        <label><BilingualText value={bi('Status', 'الحالة')} /><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All Statuses | كل الحالات</option><option value="active">Active | نشط</option></select></label>
        <span className="result-count"><SlidersHorizontal /><BilingualText value={bi(`${players.length} preview records`, `${players.length} سجلات تجريبية`)} /></span>
      </div>
    </section>
    <section className="player-table-wrap"><table className="player-table"><caption className="sr-only">Player Directory | دليل اللاعبين</caption><thead><tr>{[bi('Photo', 'الصورة'), bi('Player', 'اللاعب'), bi('Player ID', 'رقم اللاعب'), bi('Sport', 'الرياضة'), bi('Training Group', 'مجموعة التدريب'), bi('Age', 'العمر'), bi('Level', 'المستوى'), bi('Attendance', 'الحضور'), bi('Performance', 'الأداء'), bi('Status', 'الحالة'), bi('Actions', 'الإجراءات')].map(label => <th key={label.en} scope="col"><BilingualText value={label} /></th>)}</tr></thead><tbody>{players.map(player => { const sportItem = getSport(player.sportId); const group = getGroup(player.groupId); const rate = Math.round(((player.attendanceSummary?.attended ?? 0) / (player.attendanceSummary?.scheduled || 1)) * 100); return <tr key={player.id}><td><PlayerAvatar id={player.id} /></td><td><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /></td><td><code>{player.id}</code></td><td>{sportItem && <BilingualText value={sportItem.name} />}</td><td>{group && <BilingualText value={group.name} />}</td><td>{player.age}</td><td><BilingualText value={player.level} /></td><td><strong>{rate}%</strong></td><td><strong>{getPlayerOverall(player.id)}</strong><small>/ 100 | من 100</small></td><td><StatusBadge /></td><td><Link className="row-action" to={`/admin/players/${player.id}`} aria-label={`Open ${player.nameEn} | فتح ${player.nameAr}`}><ArrowRight /></Link></td></tr>; })}</tbody></table></section>
    <section className="player-mobile-list">{players.map(player => <article className="player-mobile-card" key={player.id}><div className="mobile-player-head"><PlayerAvatar id={player.id} /><BilingualText value={{ en: player.nameEn, ar: player.nameAr }} /><StatusBadge /></div><div className="mobile-player-meta"><span><BilingualText value={bi('Sport', 'الرياضة')} />{getSport(player.sportId) && <BilingualText value={getSport(player.sportId)!.name} />}</span><span><BilingualText value={bi('Group', 'المجموعة')} />{getGroup(player.groupId) && <BilingualText value={getGroup(player.groupId)!.name} />}</span><span><BilingualText value={bi('Performance', 'الأداء')} /><strong>{getPlayerOverall(player.id)} / 100</strong></span></div><Link className="admin-link-button" to={`/admin/players/${player.id}`}><BilingualText value={bi('Open Player Record', 'فتح سجل اللاعب')} /><ArrowRight /></Link></article>)}</section>
    {showForm && <div className="admin-modal-backdrop" role="presentation" onMouseDown={() => setShowForm(false)}><section className="admin-modal" role="dialog" aria-modal="true" aria-label="Add Player Preview Form | نموذج معاينة إضافة لاعب" onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><BilingualText value={bi('Add Player', 'إضافة لاعب')} /><small><BilingualText value={bi('Local Preview State Only', 'حالة معاينة محلية فقط')} /></small></div><button className="admin-icon-button" onClick={() => setShowForm(false)} aria-label="Close | إغلاق"><X /></button></div><div className="preview-warning"><BilingualText value={bi('This form does not save to a database. It prepares the future data-entry experience only.', 'هذا النموذج لا يحفظ في قاعدة بيانات. إنه يجهز تجربة إدخال البيانات المستقبلية فقط.')} /></div><div className="preview-form-grid"><label><BilingualText value={bi('Player Name', 'اسم اللاعب')} /><input placeholder="Preview name | اسم تجريبي" /></label><label><BilingualText value={bi('Player ID', 'رقم اللاعب')} /><input placeholder="player-demo-000 | لاعب-تجريبي-000" /></label><label><BilingualText value={bi('Sport', 'الرياضة')} /><select><option>Select Sport | اختر الرياضة</option>{demoSports.map(item => <option key={item.id}>{item.name.en} | {item.name.ar}</option>)}</select></label><label><BilingualText value={bi('Training Group', 'مجموعة التدريب')} /><select><option>Select Group | اختر المجموعة</option></select></label><label><BilingualText value={bi('Age Group', 'الفئة العمرية')} /><input placeholder="Age group | الفئة العمرية" /></label><label><BilingualText value={bi('Level', 'المستوى')} /><input placeholder="Level | المستوى" /></label></div><button className="admin-secondary-button" onClick={() => setShowForm(false)}><BilingualText value={bi('Close Preview Form', 'إغلاق نموذج المعاينة')} /></button></section></div>}
  </div>;
}
