import { ArrowRight, Filter, Plus, Search, SlidersHorizontal, X, Megaphone, AlertCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHeader, StatusBadge } from '../../components/admin/AdminUI';
import { BilingualText, bi } from '../../components/bilingual/BilingualText';
import { useAnnouncements, useCreateAnnouncement, useUpdateAnnouncement, useDeleteAnnouncement } from '../../admin/data/adminHooks';

export function AdminAnnouncementsPage() {
  const [query, setQuery] = useState(''); const [priority, setPriority] = useState('all'); const [status, setStatus] = useState('all'); const [showForm, setShowForm] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false);
  const { data, loading, params, setParams, refetch } = useAnnouncements({ page: 1, pageSize: 20 });
  const { create, loading: createLoading } = useCreateAnnouncement();
  const { update, loading: updateLoading } = useUpdateAnnouncement();
  const { delete: deleteFn, loading: deleteLoading } = useDeleteAnnouncement();

  const announcements = useMemo(() => data?.items.filter(ann => {
    const matchesQuery = `${ann.title.en} ${ann.title.ar} ${ann.id}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (priority === 'all' || ann.priority === priority) && (status === 'all' || ann.status === status);
  }) ?? [], [data, query, priority, status]);

  return <div className="admin-page">
    <PageHeader eyebrow={bi('Communications', 'التواصل')} title={bi('Announcements', 'الإعلانات')} description={bi('Preview of system-wide announcements and notices.', 'معاينة للإعلانات والتنبيهات على مستوى النظام.')} actions={<button className="admin-primary-button" onClick={() => setShowForm(true)}><Plus /><BilingualText value={bi('Add Announcement', 'إضافة إعلان')} /></button>} />
    <section className="player-filter-bar">
      <label className="filter-search"><Search /><span className="sr-only">Search Announcements | البحث عن الإعلانات</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Announcements | البحث عن الإعلانات" /></label>
      <button className="filter-drawer-button" onClick={() => setFiltersOpen(!filtersOpen)}><Filter /><BilingualText value={bi('Filters', 'الفلاتر')} /></button>
      <div className={`filter-fields ${filtersOpen ? 'open' : ''}`}>
        <label><BilingualText value={bi('Priority', 'الأولوية')} /><select value={priority} onChange={event => setPriority(event.target.value)}><option value="all">All Priorities | كل الأولويات</option><option value="low">Low | منخفض</option><option value="normal">Normal | عادي</option><option value="high">High | عالي</option><option value="urgent">Urgent | عاجل</option></select></label>
        <label><BilingualText value={bi('Status', 'الحالة')} /><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All Statuses | كل الحالات</option><option value="draft">Draft | مسودة</option><option value="published">Published | منشور</option><option value="archived">Archived | مؤرشف</option></select></label>
        <span className="result-count"><SlidersHorizontal /><BilingualText value={bi(`${announcements.length} preview records`, `${announcements.length} سجلات تجريبية`)} /></span>
      </div>
    </section>
    <section className="player-table-wrap"><table className="player-table"><caption className="sr-only">Announcements Directory | دليل الإعلانات</caption><thead><tr>{[bi('Announcement', 'الإعلان'), bi('Priority', 'الأولوية'), bi('Audience', 'الجمهور'), bi('Status', 'الحالة'), bi('Published', 'تاريخ النشر'), bi('Actions', 'الإجراءات')].map(label => <th key={label.en} scope="col"><BilingualText value={label} /></th>)}</tr></thead><tbody>{announcements.map(ann => <tr key={ann.id}><td><Megaphone size={16} /><BilingualText value={ann.title} /></td><td><span className={`priority-badge priority-${ann.priority}`}><BilingualText value={{ en: ann.priority, ar: ann.priority }} /></span></td><td><BilingualText value={ann.audience} /></td><td><StatusBadge active={ann.status === 'published'} /></td><td>{ann.publishedAt ? new Date(ann.publishedAt).toLocaleDateString() : <BilingualText value={bi('Not published', 'غير منشور')} />}</td><td><Link className="row-action" to={`/admin/announcements/${ann.id}`} aria-label={`Open ${ann.title.en} | فتح ${ann.title.ar}`}><ArrowRight /></Link></td></tr>)}</tbody></table></section>
    <section className="player-mobile-list">{announcements.map(ann => <article className="player-mobile-card" key={ann.id}><div className="mobile-player-head"><Megaphone size={24} /><div><BilingualText value={ann.title} /><StatusBadge active={ann.status === 'published'} /></div></div><div className="mobile-player-meta"><span><BilingualText value={bi('Priority', 'الأولوية')} /><span className={`priority-badge priority-${ann.priority}`}><BilingualText value={{ en: ann.priority, ar: ann.priority }} /></span></span><span><BilingualText value={bi('Audience', 'الجمهور')} /><BilingualText value={ann.audience} /></span><span><BilingualText value={bi('Published', 'تاريخ النشر')} />{ann.publishedAt ? new Date(ann.publishedAt).toLocaleDateString() : <BilingualText value={bi('Not published', 'غير منشور')} />}</span></div><Link className="admin-link-button" to={`/admin/announcements/${ann.id}`}><BilingualText value={bi('Open Announcement', 'فتح الإعلان')} /><ArrowRight /></Link></article>)}</section>
    {showForm && <div className="admin-modal-backdrop" role="presentation" onMouseDown={() => setShowForm(false)}><section className="admin-modal" role="dialog" aria-modal="true" aria-label="Add Announcement Preview Form | نموذج معاينة إضافة إعلان" onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><BilingualText value={bi('Add Announcement', 'إضافة إعلان')} /><small><BilingualText value={bi('Local Preview State Only', 'حالة معاينة محلية فقط')} /></small></div><button className="admin-icon-button" onClick={() => setShowForm(false)} aria-label="Close | إغلاق"><X /></button></div><div className="preview-warning"><BilingualText value={bi('This form does not save to a database. It prepares the future data-entry experience only.', 'هذا النموذج لا يحفظ في قاعدة بيانات. إنه يجهز تجربة إدخال البيانات المستقبلية فقط.')} /></div><div className="preview-form-grid"><label><BilingualText value={bi('Title', 'العنوان')} /><input placeholder="Announcement title | عنوان الإعلان" /></label><label><BilingualText value={bi('Body', 'المحتوى')} /><textarea placeholder="Announcement body | محتوى الإعلان" rows={4} /></label><label><BilingualText value={bi('Audience', 'الجمهور')} /><input placeholder="All, Parents, Coaches, etc. | الجميع، أولياء الأمور، المدربون، إلخ" /></label><label><BilingualText value={bi('Priority', 'الأولوية')} /><select><option value="low">Low | منخفض</option><option value="normal">Normal | عادي</option><option value="high">High | عالي</option><option value="urgent">Urgent | عاجل</option></select></label><label><BilingualText value={bi('Status', 'الحالة')} /><select><option value="draft">Draft | مسودة</option><option value="published">Published | منشور</option></select></label></div><button className="admin-secondary-button" onClick={() => setShowForm(false)}><BilingualText value={bi('Close Preview Form', 'إغلاق نموذج المعاينة')} /></button></section></div>}
  </div>;
}