export interface UosMediaItem {
  id: string;
  key: string;
  number: string;
  src: string;
  remoteUrl: string;
  alt: {
    ar: string;
    en: string;
  };
  width: number;
  height: number;
  aspectRatio: string;
  role: 'hero' | 'card' | 'story' | 'technique' | 'cta';
  category?: string;
}

export const UOS_PUBLIC_MEDIA: Record<string, UosMediaItem> = {
  UOS_01_HOME_HERO: {
    id: 'uos-01',
    key: 'UOS_01_HOME_HERO',
    number: '01',
    src: '/media/public/uos-01-source.png',
    remoteUrl: 'https://i.postimg.cc/fbNpLdWQ/file-00000000bacc81f4b9a9c073233596cb.png',
    alt: {
      ar: 'لاعب ناشئ من يونايتد أوليمبيكس سبورت يتدرب على كرة القدم',
      en: 'Young athlete training in football at United Olympics Sports',
    },
    width: 1279,
    height: 720,
    aspectRatio: '1279 / 720',
    role: 'hero',
    category: 'football',
  },
  UOS_02_FOOTBALL_CARD: {
    id: 'uos-02',
    key: 'UOS_02_FOOTBALL_CARD',
    number: '02',
    src: '/media/public/uos-02-source.png',
    remoteUrl: 'https://i.postimg.cc/8CS95vp3/file-0000000099fc820a8369a3d67fb2cba3.png',
    alt: {
      ar: 'لاعب ناشئ يتدرب على المراوغة والتحكم بالكرة',
      en: 'Young football player training in dribbling and ball control',
    },
    width: 640,
    height: 800,
    aspectRatio: '640 / 800',
    role: 'card',
    category: 'football',
  },
  UOS_03_SWIMMING_CARD: {
    id: 'uos-03',
    key: 'UOS_03_SWIMMING_CARD',
    number: '03',
    src: '/media/public/uos-03-source.png',
    remoteUrl: 'https://i.postimg.cc/CxD9S7g9/file-00000000d6208243b9d0a256670fb462.png',
    alt: {
      ar: 'سباح ناشئ يتدرب على السباحة الحرة',
      en: 'Young swimmer training in freestyle',
    },
    width: 640,
    height: 800,
    aspectRatio: '640 / 800',
    role: 'card',
    category: 'swimming',
  },
  UOS_04_BASKETBALL_CARD: {
    id: 'uos-04',
    key: 'UOS_04_BASKETBALL_CARD',
    number: '04',
    src: '/media/public/uos-04-source.png',
    remoteUrl: 'https://i.postimg.cc/9fhKM9Xh/file-00000000c460820aa62b5b16432fa7f6.png',
    alt: {
      ar: 'لاعب كرة سلة ناشئ يؤدي تمرين مراوغة',
      en: 'Young basketball athlete performing a dribbling drill',
    },
    width: 640,
    height: 800,
    aspectRatio: '640 / 800',
    role: 'card',
    category: 'basketball',
  },
  UOS_05_TENNIS_CARD: {
    id: 'uos-05',
    key: 'UOS_05_TENNIS_CARD',
    number: '05',
    src: '/media/public/uos-05-source.png',
    remoteUrl: 'https://i.postimg.cc/cJS2H3xD/file-00000000bd0c81f480fcd06b3ccc1b9a.png',
    alt: {
      ar: 'لاعب تنس ناشئ ينفذ ضربة أمامية أثناء التدريب',
      en: 'Young tennis athlete playing a forehand during training',
    },
    width: 640,
    height: 800,
    aspectRatio: '640 / 800',
    role: 'card',
    category: 'tennis',
  },
  UOS_06_GYMNASTICS_CARD: {
    id: 'uos-06',
    key: 'UOS_06_GYMNASTICS_CARD',
    number: '06',
    src: '/media/public/uos-06-source.jpg',
    remoteUrl: 'https://i.postimg.cc/zfr6BhDB/file-000000000a7c81f4baf99cd770452645.png',
    alt: {
      ar: 'لاعبة جمباز ناشئة تؤدي تمرين توازن',
      en: 'Young gymnast performing a balance exercise',
    },
    width: 1229,
    height: 1536,
    aspectRatio: '1229 / 1536',
    role: 'card',
    category: 'gymnastics',
  },
  UOS_07_MARTIAL_ARTS_CARD: {
    id: 'uos-07',
    key: 'UOS_07_MARTIAL_ARTS_CARD',
    number: '07',
    src: '/media/public/uos-07-source.jpg',
    remoteUrl: 'https://i.postimg.cc/SKh3s9Qk/file-000000000788820a8941d4a5b6c5c450.png',
    alt: {
      ar: 'رياضيان ناشئان يتدربان على الفنون القتالية بانضباط',
      en: 'Young athletes practising martial arts with discipline',
    },
    width: 1229,
    height: 1536,
    aspectRatio: '1229 / 1536',
    role: 'card',
    category: 'martial-arts',
  },
  UOS_08_PROGRESS_STORY: {
    id: 'uos-08',
    key: 'UOS_08_PROGRESS_STORY',
    number: '08',
    src: '/media/public/uos-08-source.jpg',
    remoteUrl: 'https://i.postimg.cc/DwsRn6Tx/file-000000008ba081f4b76b09569a6f5ca2.png',
    alt: {
      ar: 'مجموعة من الرياضيين الناشئين أثناء تدريب منظم بإشراف مدرب',
      en: 'Young athletes in an organised training session with a coach',
    },
    width: 1536,
    height: 1024,
    aspectRatio: '1536 / 1024',
    role: 'story',
    category: 'training',
  },
  UOS_09_ABOUT_HERO: {
    id: 'uos-09',
    key: 'UOS_09_ABOUT_HERO',
    number: '09',
    src: '/media/public/uos-09-source.png',
    remoteUrl: 'https://i.postimg.cc/Bv0k6FSN/file-00000000fe0882109a9f43751a363a25.png',
    alt: {
      ar: 'رياضيون ناشئون يتدربون داخل منشأة يونايتد أوليمبيكس سبورت',
      en: 'Young athletes training inside a United Olympics Sports facility',
    },
    width: 1279,
    height: 548,
    aspectRatio: '1279 / 548',
    role: 'hero',
    category: 'about',
  },
  UOS_10_ABOUT_REFLECTION: {
    id: 'uos-10',
    key: 'UOS_10_ABOUT_REFLECTION',
    number: '10',
    src: '/media/public/uos-10-source.jpg',
    remoteUrl: 'https://i.postimg.cc/JhLvnXrF/file-000000002fa882108347c5632700765e.png',
    alt: {
      ar: 'لاعب ناشئ يستعد للتدريب وينظر نحو الملعب',
      en: 'Young athlete preparing for training and looking towards the field',
    },
    width: 1536,
    height: 1024,
    aspectRatio: '1536 / 1024',
    role: 'story',
    category: 'about',
  },
  UOS_11_FOOTBALL_HERO: {
    id: 'uos-11',
    key: 'UOS_11_FOOTBALL_HERO',
    number: '11',
    src: '/media/public/uos-11-source.png',
    remoteUrl: 'https://i.postimg.cc/SKh3s9Sw/file-00000000d57881f489f67cf43f7b7f1a.png',
    alt: {
      ar: 'لاعب ناشئ يتقدم بالكرة أثناء تدريب كرة القدم',
      en: 'Young athlete carrying the ball during football training',
    },
    width: 1279,
    height: 720,
    aspectRatio: '1279 / 720',
    role: 'hero',
    category: 'football',
  },
  UOS_12_FOOTBALL_TECHNIQUE: {
    id: 'uos-12',
    key: 'UOS_12_FOOTBALL_TECHNIQUE',
    number: '12',
    src: '/media/public/uos-12-source.jpg',
    remoteUrl: 'https://i.postimg.cc/3xpzY1TP/file-00000000540481f495db5292007fc40d.png',
    alt: {
      ar: 'تفاصيل تدريب لاعب ناشئ على التحكم الدقيق بالكرة',
      en: 'Close view of a young athlete practising precise ball control',
    },
    width: 1536,
    height: 1024,
    aspectRatio: '1536 / 1024',
    role: 'technique',
    category: 'football',
  },
  UOS_13_SWIMMING_HERO: {
    id: 'uos-13',
    key: 'UOS_13_SWIMMING_HERO',
    number: '13',
    src: '/media/public/uos-13-source.jpg',
    remoteUrl: 'https://i.postimg.cc/DzTHZGvB/file-000000006da48210ab6b71dcdba377ba.png',
    alt: {
      ar: 'سباح ناشئ يتدرب داخل مسبح يونايتد أوليمبيكس سبورت',
      en: 'Young swimmer training inside a United Olympics Sports pool',
    },
    width: 1536,
    height: 864,
    aspectRatio: '1536 / 864',
    role: 'hero',
    category: 'swimming',
  },
  UOS_14_SWIMMING_TECHNIQUE: {
    id: 'uos-14',
    key: 'UOS_14_SWIMMING_TECHNIQUE',
    number: '14',
    src: '/media/public/uos-14-source.jpg',
    remoteUrl: 'https://i.postimg.cc/SKh3s9Sv/file-000000002c34820a9ccfcf8346a878eb.png',
    alt: {
      ar: 'سباح ناشئ يؤدي تمرين سباحة حرة بتقنية منظمة',
      en: 'Young swimmer performing a structured freestyle drill',
    },
    width: 1536,
    height: 1024,
    aspectRatio: '1536 / 1024',
    role: 'technique',
    category: 'swimming',
  },
  UOS_15_BASKETBALL_HERO: {
    id: 'uos-15',
    key: 'UOS_15_BASKETBALL_HERO',
    number: '15',
    src: '/media/public/uos-15-source.png',
    remoteUrl: 'https://i.postimg.cc/cJBj8J6C/file-00000000f6888246b945f6923429bc83.png',
    alt: {
      ar: 'لاعب كرة سلة ناشئ يتقدم بالكرة داخل الصالة',
      en: 'Young basketball athlete advancing with the ball indoors',
    },
    width: 1279,
    height: 720,
    aspectRatio: '1279 / 720',
    role: 'hero',
    category: 'basketball',
  },
  UOS_16_BASKETBALL_DECISION: {
    id: 'uos-16',
    key: 'UOS_16_BASKETBALL_DECISION',
    number: '16',
    src: '/media/public/uos-16-source.png',
    remoteUrl: 'https://i.postimg.cc/VNWTbN5m/file-000000009ef082109a1608154539584c.png',
    alt: {
      ar: 'مجموعة ناشئين تتدرب على التمرير والعمل الجماعي في كرة السلة',
      en: 'Young basketball athletes training in passing and teamwork',
    },
    width: 1280,
    height: 853,
    aspectRatio: '1280 / 853',
    role: 'technique',
    category: 'basketball',
  },
  UOS_17_TENNIS_HERO: {
    id: 'uos-17',
    key: 'UOS_17_TENNIS_HERO',
    number: '17',
    src: '/media/public/uos-17-source.jpg',
    remoteUrl: 'https://i.postimg.cc/9fhKM9Xm/file-000000005dd481f4b42998c8f9ed3cd6.png',
    alt: {
      ar: 'لاعب تنس ناشئ يتدرب داخل ملعب يونايتد أوليمبيكس سبورت',
      en: 'Young tennis athlete training on a United Olympics Sports court',
    },
    width: 1536,
    height: 864,
    aspectRatio: '1536 / 864',
    role: 'hero',
    category: 'tennis',
  },
  UOS_18_GYMNASTICS_HERO: {
    id: 'uos-18',
    key: 'UOS_18_GYMNASTICS_HERO',
    number: '18',
    src: '/media/public/uos-18-source.png',
    remoteUrl: 'https://i.postimg.cc/VNWTbN5s/file-00000000edb88210b32581b03ddcbf05.png',
    alt: {
      ar: 'لاعبة جمباز ناشئة تؤدي تمرين توازن داخل المنشأة الرياضية',
      en: 'Young gymnast performing a balance drill inside the sports facility',
    },
    width: 1279,
    height: 720,
    aspectRatio: '1279 / 720',
    role: 'hero',
    category: 'gymnastics',
  },
  UOS_19_MARTIAL_ARTS_HERO: {
    id: 'uos-19',
    key: 'UOS_19_MARTIAL_ARTS_HERO',
    number: '19',
    src: '/media/public/uos-19-source.jpg',
    remoteUrl: 'https://i.postimg.cc/QM3wt7Ns/file-000000004ee48210aa2827f372a4d166.png',
    alt: {
      ar: 'رياضيان ناشئان يظهران الاحترام والانضباط في تدريب الفنون القتالية',
      en: 'Young athletes showing respect and discipline in martial arts training',
    },
    width: 1536,
    height: 864,
    aspectRatio: '1536 / 864',
    role: 'hero',
    category: 'martial-arts',
  },
  UOS_20_CLOSING_CTA: {
    id: 'uos-20',
    key: 'UOS_20_CLOSING_CTA',
    number: '20',
    src: '/media/public/uos-20-source.jpg',
    remoteUrl: 'https://i.postimg.cc/W4vC3ZpP/file-000000004ea48243acf35ee8f1ddd0a0.png',
    alt: {
      ar: 'رياضيون ناشئون داخل بيئة يونايتد أوليمبيكس سبورت التدريبية',
      en: 'Young athletes in the United Olympics Sports training environment',
    },
    width: 1536,
    height: 658,
    aspectRatio: '1536 / 658',
    role: 'cta',
    category: 'all',
  },
} as const;

export default UOS_PUBLIC_MEDIA;
